% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\usepackage{float}
\usepackage{tabularray}
\usepackage[normalem]{ulem}
\usepackage{graphicx}
\UseTblrLibrary{booktabs}
\UseTblrLibrary{rotating}
\UseTblrLibrary{siunitx}
\NewTableCommand{\tinytableDefineColor}[3]{\definecolor{#1}{#2}{#3}}
\newcommand{\tinytableTabularrayUnderline}[1]{\underline{#1}}
\newcommand{\tinytableTabularrayStrikeout}[1]{\sout{#1}}
\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Trabalho de Avaliação de Políticas Sociais},
  pdfauthor={Ana Di Nur, Gabriel Figueiredo, Tiago Brancher},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Trabalho de Avaliação de Políticas Sociais}
\author{Ana Di Nur, Gabriel Figueiredo, Tiago Brancher}
\date{}

\begin{document}
\maketitle


\begin{itemize}
\item
  Diferença em relação à versão de 14/11/2025: Vou juntar
  dt\_municipios\_eleicoes com dt\_emendas antes de cada exercício em
  vez de tentar juntar tudo no começo e ir alterando depois.
\item
  Diferença em relação à versão de 15/11/2025: Mudei os dados
  selecionados de características municipais (para serem mais recentes)
  e a fonte de dados de emendas parlamentares (para que o ano da emenda
  refletisse seu ano de empenho, não proposição)
\end{itemize}

\section{0) Preparativos}\label{preparativos}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(readxl) }\CommentTok{\# para obtenção dos dados}
\FunctionTok{library}\NormalTok{(basedosdados) }\CommentTok{\# para obtenção dos dados}
\FunctionTok{library}\NormalTok{(dplyr) }\CommentTok{\# para transformação dos dados}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Attaching package: 'dplyr'
\end{verbatim}

\begin{verbatim}
The following objects are masked from 'package:stats':

    filter, lag
\end{verbatim}

\begin{verbatim}
The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(data.table) }\CommentTok{\# para transformação dos dados}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Attaching package: 'data.table'
\end{verbatim}

\begin{verbatim}
The following objects are masked from 'package:dplyr':

    between, first, last
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(janitor) }\CommentTok{\# para transformação dos dados}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

Attaching package: 'janitor'
\end{verbatim}

\begin{verbatim}
The following objects are masked from 'package:stats':

    chisq.test, fisher.test
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2) }\CommentTok{\# para visualização dos dados}
\FunctionTok{library}\NormalTok{(cowplot) }\CommentTok{\# para visualização dos dados (plotá{-}los lado a lado)}
\FunctionTok{library}\NormalTok{(scales) }\CommentTok{\# para visualização dos dados (fazer eixos bonito)}
\FunctionTok{library}\NormalTok{(estimatr) }\CommentTok{\# para modelagem}
\FunctionTok{library}\NormalTok{(modelsummary) }\CommentTok{\# para visualização de resultados dos modelos}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
`modelsummary` 2.0.0 now uses `tinytable` as its default table-drawing
  backend. Learn more at: https://vincentarelbundock.github.io/tinytable/

Revert to `kableExtra` for one session:

  options(modelsummary_factory_default = 'kableExtra')
  options(modelsummary_factory_latex = 'kableExtra')
  options(modelsummary_factory_html = 'kableExtra')

Silence this message forever:

  config_modelsummary(startup_message = FALSE)
\end{verbatim}

\section{1) Coleta e junção de
dados}\label{coleta-e-junuxe7uxe3o-de-dados}

\subsection{1.1) Coleta de dados}\label{coleta-de-dados}

\subsubsection{1.1.1) Características
municipais}\label{caracteruxedsticas-municipais}

\begin{itemize}
\item
  Origem dos dados: Acessar \href{https://cidades.ibge.gov.br/}{IBGE
  Cidades} \textgreater{} Selecionar UFs \textgreater{} Selecionar
  variáveis de interesse

  \begin{itemize}
  \item
    Hipótese: Perfil municipal não mudou significativamente entre os
    anos de coleta dos dados (2021, 2022) e o ano da eleição (2020) e do
    empenho das emendas (2021)
  \item
    Variáveis selecionadas:

    \begin{itemize}
    \item
      População no último censo (2022)
    \item
      Densidade demográfica (2022)
    \item
      PIB \emph{per capita} municipal (2021)
    \item
      Taxa de escolarização de 6 a 14 anos de idade (2022)
    \item
      Mortalidade infantil (2023)
    \end{itemize}
  \end{itemize}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Carregar planilha montada a partir dos relatórios do IBGE Cidades}
\NormalTok{dt\_municipios }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"Bases de dados/Brasil/IBGE\_municipios.xlsx"}\NormalTok{)}
\FunctionTok{setDT}\NormalTok{(dt\_municipios)}

\CommentTok{\# Renomear colunas}
\NormalTok{nomes }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"id\_municipio\_nome"}\NormalTok{, }\StringTok{"sigla\_uf"}\NormalTok{, }\StringTok{"mortalidade\_infantil"}\NormalTok{, }\StringTok{"PIBpc"}\NormalTok{, }\StringTok{"taxa\_escolarizacao"}\NormalTok{, }\StringTok{"pop"}\NormalTok{, }\StringTok{"densidade\_demografica"}\NormalTok{)}
\FunctionTok{colnames}\NormalTok{(dt\_municipios) }\OtherTok{\textless{}{-}}\NormalTok{ nomes}
\FunctionTok{rm}\NormalTok{(nomes)}

\CommentTok{\# Transformar gentílico na sigla do UF}
\NormalTok{dt\_municipios[, sigla\_uf }\SpecialCharTok{:}\ErrorTok{=} \FunctionTok{fcase}\NormalTok{(}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"acriano"}\NormalTok{, }\StringTok{"AC"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"alagoano"}\NormalTok{, }\StringTok{"AL"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"amapaense"}\NormalTok{, }\StringTok{"AP"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"amazonense"}\NormalTok{, }\StringTok{"AM"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"baiano"}\NormalTok{, }\StringTok{"BA"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"cearense"}\NormalTok{, }\StringTok{"CE"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"brasiliense"}\NormalTok{, }\StringTok{"DF"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"capixaba ou espírito{-}santense"}\NormalTok{, }\StringTok{"ES"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"goiano"}\NormalTok{, }\StringTok{"GO"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"maranhense"}\NormalTok{, }\StringTok{"MA"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"mato{-}grossense"}\NormalTok{, }\StringTok{"MT"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"sul{-}mato{-}grossense ou mato{-}grossense{-}do{-}sul"}\NormalTok{, }\StringTok{"MS"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"mineiro"}\NormalTok{, }\StringTok{"MG"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"paranaense"}\NormalTok{, }\StringTok{"PR"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"paraibano"}\NormalTok{, }\StringTok{"PB"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"paraense"}\NormalTok{, }\StringTok{"PA"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"pernambucano"}\NormalTok{, }\StringTok{"PE"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"piauiense"}\NormalTok{, }\StringTok{"PI"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"potiguar, norte{-}rio{-}grandense, rio{-}grandense{-}do{-}norte"}\NormalTok{, }\StringTok{"RN"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"gaúcho ou sul{-}rio{-}grandense"}\NormalTok{, }\StringTok{"RS"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"fluminense"}\NormalTok{, }\StringTok{"RJ"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"rondoniense ou rondoniano"}\NormalTok{, }\StringTok{"RO"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"roraimense"}\NormalTok{, }\StringTok{"RR"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"catarinense ou barriga{-}verde"}\NormalTok{, }\StringTok{"SC"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"sergipano ou sergipense"}\NormalTok{, }\StringTok{"SE"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"paulista"}\NormalTok{, }\StringTok{"SP"}\NormalTok{,}
\NormalTok{  sigla\_uf }\SpecialCharTok{==} \StringTok{"tocantinense"}\NormalTok{, }\StringTok{"TO"}
\NormalTok{)]}

\CommentTok{\# Criar coluna de região}
\NormalTok{dt\_municipios[, regiao }\SpecialCharTok{:}\ErrorTok{=} \FunctionTok{fcase}\NormalTok{(}
\NormalTok{    sigla\_uf }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"AC"}\NormalTok{, }\StringTok{"AM"}\NormalTok{, }\StringTok{"AP"}\NormalTok{, }\StringTok{"PA"}\NormalTok{, }\StringTok{"RO"}\NormalTok{, }\StringTok{"RR"}\NormalTok{, }\StringTok{"TO"}\NormalTok{), }\StringTok{"Norte"}\NormalTok{,}
\NormalTok{    sigla\_uf }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"AL"}\NormalTok{, }\StringTok{"BA"}\NormalTok{, }\StringTok{"CE"}\NormalTok{, }\StringTok{"MA"}\NormalTok{, }\StringTok{"PE"}\NormalTok{, }\StringTok{"PB"}\NormalTok{, }\StringTok{"PI"}\NormalTok{, }\StringTok{"RN"}\NormalTok{, }\StringTok{"SE"}\NormalTok{), }\StringTok{"Nordeste"}\NormalTok{,}
\NormalTok{    sigla\_uf }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"DF"}\NormalTok{, }\StringTok{"GO"}\NormalTok{, }\StringTok{"MS"}\NormalTok{, }\StringTok{"MT"}\NormalTok{), }\StringTok{"Centro{-}Oeste"}\NormalTok{,}
\NormalTok{    sigla\_uf }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"ES"}\NormalTok{, }\StringTok{"MG"}\NormalTok{, }\StringTok{"RJ"}\NormalTok{, }\StringTok{"SP"}\NormalTok{), }\StringTok{"Sudeste"}\NormalTok{,}
\NormalTok{    sigla\_uf }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"PR"}\NormalTok{, }\StringTok{"RS"}\NormalTok{, }\StringTok{"SC"}\NormalTok{), }\StringTok{"Sul"}\NormalTok{)]}

\CommentTok{\# Transformar colunas em variáveis numéricas}
\DocumentationTok{\#\# Inteiros}
\NormalTok{dt\_municipios[, pop }\SpecialCharTok{:}\ErrorTok{=} \FunctionTok{gsub}\NormalTok{(}\StringTok{"[\^{}0{-}9.{-}]"}\NormalTok{, }\StringTok{""}\NormalTok{, pop) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{as.numeric}\NormalTok{()]}
\DocumentationTok{\#\# Decimais}
\NormalTok{dt\_municipios[,}
\NormalTok{  densidade\_demografica }\SpecialCharTok{:}\ErrorTok{=} \FunctionTok{as.numeric}\NormalTok{(}
    \FunctionTok{gsub}\NormalTok{(}\StringTok{","}\NormalTok{, }\StringTok{"."}\NormalTok{, }\FunctionTok{gsub}\NormalTok{(}\StringTok{"[\^{}0{-}9,]"}\NormalTok{, }\StringTok{""}\NormalTok{, densidade\_demografica))}
\NormalTok{  )}
\NormalTok{]}
\NormalTok{dt\_municipios[,}
\NormalTok{  mortalidade\_infantil }\SpecialCharTok{:}\ErrorTok{=} \FunctionTok{as.numeric}\NormalTok{(}
    \FunctionTok{gsub}\NormalTok{(}\StringTok{","}\NormalTok{, }\StringTok{"."}\NormalTok{, }\FunctionTok{gsub}\NormalTok{(}\StringTok{"[\^{}0{-}9,]"}\NormalTok{, }\StringTok{""}\NormalTok{, mortalidade\_infantil))}
\NormalTok{  )}
\NormalTok{]}
\NormalTok{dt\_municipios[,}
\NormalTok{  PIBpc }\SpecialCharTok{:}\ErrorTok{=} \FunctionTok{as.numeric}\NormalTok{(}
    \FunctionTok{gsub}\NormalTok{(}\StringTok{","}\NormalTok{, }\StringTok{"."}\NormalTok{, }\FunctionTok{gsub}\NormalTok{(}\StringTok{"[\^{}0{-}9,]"}\NormalTok{, }\StringTok{""}\NormalTok{, PIBpc))}
\NormalTok{  )}
\NormalTok{]}
\NormalTok{dt\_municipios[,}
\NormalTok{  taxa\_escolarizacao }\SpecialCharTok{:}\ErrorTok{=} \FunctionTok{as.numeric}\NormalTok{(}
    \FunctionTok{gsub}\NormalTok{(}\StringTok{","}\NormalTok{, }\StringTok{"."}\NormalTok{, }\FunctionTok{gsub}\NormalTok{(}\StringTok{"[\^{}0{-}9,]"}\NormalTok{, }\StringTok{""}\NormalTok{, taxa\_escolarizacao))}
\NormalTok{  )}\SpecialCharTok{/}\DecValTok{100}
\NormalTok{]}

\CommentTok{\# Dar uma olhada na base}
\FunctionTok{str}\NormalTok{(dt\_municipios)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Classes 'data.table' and 'data.frame':  5571 obs. of  8 variables:
 $ id_municipio_nome    : chr  "Acrelândia" "Assis Brasil" "Brasiléia" "Bujari" ...
 $ sigla_uf             : chr  "AC" "AC" "AC" "AC" ...
 $ mortalidade_infantil : num  NA 7.78 5.78 19.53 11.11 ...
 $ PIBpc                : num  25363 17508 25279 28455 41723 ...
 $ taxa_escolarizacao   : num  0.961 0.957 0.959 0.957 0.96 ...
 $ pop                  : num  14021 8100 26000 12917 10392 ...
 $ densidade_demografica: num  7.74 1.63 6.62 4.26 6.09 ...
 $ regiao               : chr  "Norte" "Norte" "Norte" "Norte" ...
 - attr(*, ".internal.selfref")=<externalptr> 
\end{verbatim}

\subsubsection{1.1.2) Eleições}\label{eleiuxe7uxf5es}

\begin{itemize}
\tightlist
\item
  Origem dos dados: Acessar
  \href{https://basedosdados.org/dataset/eef764df-bde8-4905-b115-6fc23b6ba9d6?table=391047eb-b3ef-4141-a4d1-725b29018f25}{Base
  dos Dados \textgreater{} Eleições Brasileiras} \textgreater{}
  Resultados por Candidato e Município
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# \# Fazer query}
\CommentTok{\# query \textless{}{-} "SELECT}
\CommentTok{\#     dados.ano AS ano,}
\CommentTok{\#     dados.turno AS turno,}
\CommentTok{\#     dados.sigla\_uf AS sigla\_uf,}
\CommentTok{\#     diretorio\_sigla\_uf.nome AS sigla\_uf\_nome,}
\CommentTok{\#     dados.id\_municipio AS id\_municipio,}
\CommentTok{\#     diretorio\_id\_municipio.nome AS id\_municipio\_nome,}
\CommentTok{\#     dados.cargo AS cargo,}
\CommentTok{\#     dados.numero\_partido AS numero\_partido,}
\CommentTok{\#     dados.sigla\_partido AS sigla\_partido,}
\CommentTok{\#     dados.resultado AS resultado,}
\CommentTok{\#     dados.votos AS votos}
\CommentTok{\# FROM \textasciigrave{}basedosdados.br\_tse\_eleicoes.resultados\_candidato\_municipio\textasciigrave{} AS dados}
\CommentTok{\# LEFT JOIN (}
\CommentTok{\#     SELECT DISTINCT sigla, nome  }
\CommentTok{\#     FROM \textasciigrave{}basedosdados.br\_bd\_diretorios\_brasil.uf\textasciigrave{}}
\CommentTok{\# ) AS diretorio\_sigla\_uf}
\CommentTok{\#     ON dados.sigla\_uf = diretorio\_sigla\_uf.sigla}
\CommentTok{\# LEFT JOIN (}
\CommentTok{\#     SELECT DISTINCT id\_municipio, nome  }
\CommentTok{\#     FROM \textasciigrave{}basedosdados.br\_bd\_diretorios\_brasil.municipio\textasciigrave{}}
\CommentTok{\# ) AS diretorio\_id\_municipio}
\CommentTok{\#     ON dados.id\_municipio = diretorio\_id\_municipio.id\_municipio}
\CommentTok{\# WHERE }
\CommentTok{\#     dados.ano IN (2020)}
\CommentTok{\#     AND dados.cargo = \textquotesingle{}prefeito\textquotesingle{}}
\CommentTok{\# "}
\CommentTok{\# dt\_eleicoes \textless{}{-} read\_sql(query, billing\_project\_id = "pub{-}450900")}
\CommentTok{\# setDT(dt\_eleicoes)}
\CommentTok{\# rm(query)}
\CommentTok{\# }
\CommentTok{\# \# Salvar base de dados resultante}
\CommentTok{\# saveRDS(dt\_eleicoes, "Bases de dados/Brasil/TSE\_eleicoes.rds")}


\CommentTok{\# Carregar base de dados de eleições}
\NormalTok{dt\_eleicoes }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\StringTok{"Bases de dados/Brasil/TSE\_eleicoes.rds"}\NormalTok{)}
\FunctionTok{setDT}\NormalTok{(dt\_eleicoes)}

\CommentTok{\# Retirar primeiro turno dos municípios que tiveram segundo turno}
\NormalTok{municipios\_com\_segundo\_turno }\OtherTok{\textless{}{-}}\NormalTok{ dt\_eleicoes[turno }\SpecialCharTok{==} \DecValTok{2}\NormalTok{, }\FunctionTok{unique}\NormalTok{(id\_municipio)]}
\NormalTok{dt\_eleicoes }\OtherTok{\textless{}{-}}\NormalTok{ dt\_eleicoes[}\SpecialCharTok{!}\NormalTok{(turno }\SpecialCharTok{==} \DecValTok{1} \SpecialCharTok{\&}
\NormalTok{                               id\_municipio }\SpecialCharTok{\%in\%}\NormalTok{ municipios\_com\_segundo\_turno)]}
\FunctionTok{rm}\NormalTok{(municipios\_com\_segundo\_turno)}

\CommentTok{\# Selecionar os dois candidatos mais votados}
\FunctionTok{setorder}\NormalTok{(dt\_eleicoes, }\SpecialCharTok{{-}}\NormalTok{votos)}
\NormalTok{dt\_eleicoes }\OtherTok{\textless{}{-}}\NormalTok{ dt\_eleicoes[, }\FunctionTok{head}\NormalTok{(.SD, }\DecValTok{2}\NormalTok{), by }\OtherTok{=}\NormalTok{ id\_municipio]}

\CommentTok{\# Definir razão de votos dos top 2 (contando somente os votos desses 2)}
\NormalTok{dt\_eleicoes[, votos\_total }\SpecialCharTok{:}\ErrorTok{=} \FunctionTok{sum}\NormalTok{(votos), by }\OtherTok{=}\NormalTok{ id\_municipio]}
\NormalTok{dt\_eleicoes[, votos\_razao }\SpecialCharTok{:}\ErrorTok{=}\NormalTok{ votos}\SpecialCharTok{/}\NormalTok{votos\_total]}

\CommentTok{\# Retirar municípios em que nenhum dos dois primeiros colocados são do PP}
\NormalTok{municipios\_com\_candidato\_pp }\OtherTok{\textless{}{-}}\NormalTok{ dt\_eleicoes[sigla\_partido }\SpecialCharTok{==} \StringTok{"PP"}\NormalTok{, }\FunctionTok{unique}\NormalTok{(id\_municipio)]}
\NormalTok{dt\_eleicoes }\OtherTok{\textless{}{-}}\NormalTok{ dt\_eleicoes[id\_municipio }\SpecialCharTok{\%in\%}\NormalTok{ municipios\_com\_candidato\_pp]}
\FunctionTok{rm}\NormalTok{(municipios\_com\_candidato\_pp)}

\CommentTok{\# Selecionar municípios em que a margem de vitória foi de 5\% ou menos}
\NormalTok{dt\_eleicoes }\OtherTok{\textless{}{-}}\NormalTok{ dt\_eleicoes[votos\_razao }\SpecialCharTok{\textgreater{}=} \FloatTok{0.45} \SpecialCharTok{\&}\NormalTok{ votos\_razao }\SpecialCharTok{\textless{}=} \FloatTok{0.55}\NormalTok{]}

\CommentTok{\# Criar dummy que indica se o candidato do PP ganhou}
\NormalTok{municipios\_com\_vitoria\_pp }\OtherTok{\textless{}{-}}\NormalTok{ dt\_eleicoes[sigla\_partido }\SpecialCharTok{==} \StringTok{"PP"} \SpecialCharTok{\&}\NormalTok{ resultado }\SpecialCharTok{==} \StringTok{"eleito"}\NormalTok{,}
                                         \FunctionTok{unique}\NormalTok{(id\_municipio)]}
\NormalTok{dt\_eleicoes[, vitoria\_pp }\SpecialCharTok{:}\ErrorTok{=} \FunctionTok{ifelse}\NormalTok{(id\_municipio }\SpecialCharTok{\%in\%}\NormalTok{ municipios\_com\_vitoria\_pp, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)]}
\FunctionTok{rm}\NormalTok{(municipios\_com\_vitoria\_pp)}

\CommentTok{\# Selecionar só colunas e linhas relevantes}
\NormalTok{dt\_eleicoes }\OtherTok{\textless{}{-}}\NormalTok{ dt\_eleicoes[}
\NormalTok{  sigla\_partido }\SpecialCharTok{==} \StringTok{"PP"}\NormalTok{,}
\NormalTok{  .(}
\NormalTok{    id\_municipio,}
\NormalTok{    id\_municipio\_nome,}
\NormalTok{    sigla\_uf,}
\NormalTok{    vitoria\_pp,}
\NormalTok{    votos\_razao}
\NormalTok{  )}
\NormalTok{]}
\FunctionTok{setnames}\NormalTok{(dt\_eleicoes, }\StringTok{"votos\_razao"}\NormalTok{, }\StringTok{"votos\_razao\_pp"}\NormalTok{)}

\CommentTok{\# Criar coluna com razão de votos centralizada}
\NormalTok{dt\_eleicoes[, votos\_razao\_pp\_centr }\SpecialCharTok{:}\ErrorTok{=}\NormalTok{ votos\_razao\_pp }\SpecialCharTok{{-}} \FloatTok{0.5}\NormalTok{]}

\CommentTok{\# Criar coluna com razão de votos centralizada ao quadrado}
\NormalTok{dt\_eleicoes[, votos\_razao\_pp\_centr\_sq }\SpecialCharTok{:}\ErrorTok{=}\NormalTok{ votos\_razao\_pp\_centr}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{]}

\CommentTok{\# Dar uma olhada na base de dados resultante}
\FunctionTok{str}\NormalTok{(dt\_eleicoes)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Classes 'data.table' and 'data.frame':  487 obs. of  7 variables:
 $ id_municipio           : chr  "2507507" "1100205" "2408003" "3302502" ...
 $ id_municipio_nome      : chr  "João Pessoa" "Porto Velho" "Mossoró" "Magé" ...
 $ sigla_uf               : chr  "PB" "RO" "RN" "RJ" ...
 $ vitoria_pp             : num  1 0 0 1 1 1 1 0 1 1 ...
 $ votos_razao_pp         : num  0.532 0.456 0.475 0.544 0.52 ...
 $ votos_razao_pp_centr   : num  0.0316 -0.0445 -0.0252 0.0435 0.0197 ...
 $ votos_razao_pp_centr_sq: num  0.001001 0.00198 0.000634 0.001896 0.000387 ...
 - attr(*, ".internal.selfref")=<externalptr> 
\end{verbatim}

Note que:

5567 municípios brasileiros tiveram eleições para prefeito em 2020;

1203 (22\% dos 5567) tiveram um candidato do PP entre os dois candidatos
mais votados;

\begin{itemize}
\tightlist
\item
  487 (40\% dos 1203 e 9\% dos 5567) tiveram uma eleição acirrada (isto
  é, na qual o candidato eleito teve no máximo 55\% da soma dos votos
  nos dois candidatos mais populares).
\end{itemize}

\subsubsection{1.1.3) Emendas
parlamentares}\label{emendas-parlamentares}

\begin{itemize}
\tightlist
\item
  A base principal virá do Siga Brasil. No entanto, essa base não contém
  o código IBGE do município favorecido pela emenda. Por isso, vamos
  começar carregando dados da Base dos Dados (originados nos dados da
  CGU) que associam o identificador da emenda parlamentar ao município
  de destinação.
\item
  Origem dos dados:
  \href{https://basedosdados.org/dataset/257e000c-1685-418a-88d9-4908ccef2840?table=f116068d-b65d-4d04-9bcb-368e70062c4b}{Base
  dos Dados \textgreater{} Emendas Parlamentares}

  \begin{itemize}
  \tightlist
  \item
    Variáveis selecionadas:

    \begin{itemize}
    \tightlist
    \item
      ano\_emenda

      \begin{itemize}
      \tightlist
      \item
        Filtro: ``2021''

        \begin{itemize}
        \tightlist
        \item
          Apesar de essa variável representar o ano em que a emenda foi
          proposta, não o ano do empenho, o Siga Brasil mostra que todas
          as 1183 emendas destinadas a municípios com empenho em 2021
          foram propostas em 2021.
        \end{itemize}
      \end{itemize}
    \item
      id\_emenda
    \item
      numero\_emenda
    \item
      id\_municipio\_gasto
    \end{itemize}
  \end{itemize}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# \# Fazer query}
\CommentTok{\# query \textless{}{-} "}
\CommentTok{\# SELECT}
\CommentTok{\#     dados.id\_emenda as id\_emenda,}
\CommentTok{\#     dados.ano\_emenda as ano\_emenda,}
\CommentTok{\#     dados.id\_autor\_emenda as id\_autor\_emenda,}
\CommentTok{\#     dados.numero\_emenda as numero\_emenda,}
\CommentTok{\#     dados.id\_municipio\_gasto as id\_municipio}
\CommentTok{\# FROM \textasciigrave{}basedosdados.br\_cgu\_emendas\_parlamentares.microdados\textasciigrave{} AS dados}
\CommentTok{\# WHERE }
\CommentTok{\#     dados.ano\_emenda IN (2021)}
\CommentTok{\# "}
\CommentTok{\# de\_para\_emendas\_municipios \textless{}{-} read\_sql(query, billing\_project\_id = "pub{-}450900")}
\CommentTok{\# setDT(de\_para\_emendas\_municipios)}
\CommentTok{\# rm(query)}
\CommentTok{\# }
\CommentTok{\# \# Criar emenda (número/ano) igual à base de emendas do Siga Brasil}
\CommentTok{\# de\_para\_emendas\_municipios[, emenda\_numero\_ano := paste0(id\_autor\_emenda,}
\CommentTok{\#                                                          numero\_emenda,}
\CommentTok{\#                                                          "{-}",}
\CommentTok{\#                                                          ano\_emenda)]}
\CommentTok{\# }
\CommentTok{\# \# Selecionar somente as colunas de de{-}para}
\CommentTok{\# de\_para\_emendas\_municipios \textless{}{-} de\_para\_emendas\_municipios[, .(emenda\_numero\_ano, id\_municipio)]}
\CommentTok{\# }
\CommentTok{\# \# Salvar base de dados resultante}
\CommentTok{\# saveRDS(de\_para\_emendas\_municipios, "Bases de dados/Brasil/BD\_id\_emenda\_municipio.rds")}

\CommentTok{\# Carregar base de dados que relaciona emendas e municípios (por código do IBGE)}
\NormalTok{de\_para\_emendas\_municipios }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\StringTok{"Bases de dados/Brasil/BD\_id\_emenda\_municipio.rds"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  Origem dos dados:
  \href{https://www9qs.senado.leg.br/extensions/Siga_Brasil_Emendas/Siga_Brasil_Emendas.html}{Senado
  Federal \textgreater{} Portal do Orçamento \textgreater{} Siga Brasil
  \textgreater{} Painel Emendas} \textgreater{} Gráficos customizados

  \begin{itemize}
  \tightlist
  \item
    Variáveis selecionadas:

    \begin{itemize}
    \tightlist
    \item
      Autor (Tipo)
    \item
      Emenda (Número-Ano)
    \item
      Empenho (Ano)

      \begin{itemize}
      \tightlist
      \item
        Filtro: ``2021''
      \end{itemize}
    \item
      Função (Desc)
    \item
      Funcional Localidade (Desc)
    \item
      Funcional Localidade (Tipo)

      \begin{itemize}
      \tightlist
      \item
        Filtro: ``MUNICÍPIO''
      \end{itemize}
    \item
      GND (Desc)
    \item
      Empenhado (IPCA)
    \end{itemize}
  \end{itemize}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Carregar base de dados de emendas parlamentares}
\NormalTok{dt\_emendas }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"Bases de dados/Brasil/SigaBrasil\_emendas.xlsx"}\NormalTok{)}
\FunctionTok{setDT}\NormalTok{(dt\_emendas)}

\CommentTok{\# Renomear colunas}
\FunctionTok{colnames}\NormalTok{(dt\_emendas) }\OtherTok{\textless{}{-}} \FunctionTok{make\_clean\_names}\NormalTok{(}\FunctionTok{colnames}\NormalTok{(dt\_emendas))}

\CommentTok{\# Juntar com informação de códigos IBGE}
\NormalTok{dt\_emendas }\OtherTok{\textless{}{-}} \FunctionTok{merge}\NormalTok{(dt\_emendas, de\_para\_emendas\_municipios, }\AttributeTok{all.x =}\NormalTok{ T)}
\FunctionTok{rm}\NormalTok{(de\_para\_emendas\_municipios)}

\CommentTok{\# Substituir id\_municipio manualmente para as 4 emendas sem essa informação na base}
\DocumentationTok{\#\# Campo Grande (MS)}
\NormalTok{dt\_emendas[emenda\_numero\_ano }\SpecialCharTok{==} \StringTok{"14510004{-}2021"}\NormalTok{ , id\_municipio }\SpecialCharTok{:}\ErrorTok{=} \StringTok{"5002704"}\NormalTok{]}
\NormalTok{dt\_emendas[emenda\_numero\_ano }\SpecialCharTok{==} \StringTok{"37390008{-}2021"}\NormalTok{, id\_municipio }\SpecialCharTok{:}\ErrorTok{=} \StringTok{"2504009"}\NormalTok{]}
\NormalTok{dt\_emendas[emenda\_numero\_ano }\SpecialCharTok{==} \StringTok{"40680005{-}2021"}\NormalTok{, id\_municipio }\SpecialCharTok{:}\ErrorTok{=} \StringTok{"1301605"}\NormalTok{]}

\CommentTok{\# Garantir que não há NAs}
\FunctionTok{colSums}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(dt\_emendas))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
        emenda_numero_ano                autor_tipo       ano_emissao_empenho 
                        0                         0                         0 
                   funcao      funcional_localidade funcional_localidade_tipo 
                        0                         0                         0 
                 gnd_desc            empenhado_ipca              id_municipio 
                        0                         0                         0 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Renomear coluna de tipo}
\FunctionTok{setnames}\NormalTok{(dt\_emendas, }\StringTok{"autor\_tipo"}\NormalTok{, }\StringTok{"tipo\_emenda"}\NormalTok{)}

\CommentTok{\# Resumir dados por município, tipo de emenda, função e GND e armazenar dt para eventuais análises de heterogeneidade}
\NormalTok{dt\_emendas\_com\_funcao\_gnd }\OtherTok{\textless{}{-}}\NormalTok{ dt\_emendas[,}
\NormalTok{  .(}\AttributeTok{valor\_empenhado\_ipca =} \FunctionTok{sum}\NormalTok{(empenhado\_ipca)),}
\NormalTok{  by }\OtherTok{=}\NormalTok{ .(id\_municipio, tipo\_emenda, funcao, gnd\_desc)}
\NormalTok{]}

\CommentTok{\# Resumir dados por município e tipo de emenda}
\NormalTok{dt\_emendas }\OtherTok{\textless{}{-}}\NormalTok{ dt\_emendas[,}
\NormalTok{  .(}\AttributeTok{valor\_empenhado\_ipca =} \FunctionTok{sum}\NormalTok{(empenhado\_ipca)),}
\NormalTok{  by }\OtherTok{=}\NormalTok{ .(id\_municipio, tipo\_emenda)}
\NormalTok{]}

\CommentTok{\# Ver quantos municípios foram favorecidos por algum empenho de emenda em 2021}
\FunctionTok{length}\NormalTok{(dt\_emendas[, }\FunctionTok{unique}\NormalTok{(id\_municipio)])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 666
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Ver quais tipos de emendas há na base}
\NormalTok{dt\_emendas[, }\FunctionTok{unique}\NormalTok{(tipo\_emenda)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "INDIVIDUAL"              "BANCADA ESTADUAL (RP 7)"
[3] "RELATOR (RP 9)"         
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Simplificar nome do tipo de emenda}
\NormalTok{dt\_emendas[, tipo\_emenda }\SpecialCharTok{:}\ErrorTok{=} \FunctionTok{fcase}\NormalTok{(}
\NormalTok{  tipo\_emenda }\SpecialCharTok{==} \StringTok{"INDIVIDUAL"}\NormalTok{, }\StringTok{"individual"}\NormalTok{,}
\NormalTok{  tipo\_emenda }\SpecialCharTok{==} \StringTok{"BANCADA ESTADUAL (RP 7)"}\NormalTok{, }\StringTok{"bancada"}\NormalTok{,}
\NormalTok{  tipo\_emenda }\SpecialCharTok{==} \StringTok{"RELATOR (RP 9)"}\NormalTok{, }\StringTok{"relator"}
\NormalTok{)]}

\CommentTok{\# Dar uma olhada na base}
\FunctionTok{head}\NormalTok{(dt\_emendas)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   id_municipio tipo_emenda valor_empenhado_ipca
         <char>      <char>                <num>
1:      2607109  individual             122383.8
2:      2612604  individual             131423.8
3:      2607000  individual             252882.8
4:      2603009  individual             316103.5
5:      2210201  individual             255310.4
6:      2206670  individual             379324.2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Resumir valor empenhado de emendas por tipo}
\NormalTok{dt\_emendas[, .(}\AttributeTok{valor\_empenhado\_ipca =} \FunctionTok{sum}\NormalTok{(valor\_empenhado\_ipca)), by }\OtherTok{=}\NormalTok{ tipo\_emenda]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
   tipo_emenda valor_empenhado_ipca
        <char>                <num>
1:  individual            943753489
2:     bancada           1482525667
3:     relator             15760159
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Resumir qtde de municípios que receberam cada tipo de emenda}
\FunctionTok{writeLines}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}
  \StringTok{"Quantidade de municípios a receberem qualquer tipo de emenda: "}\NormalTok{, }\FunctionTok{length}\NormalTok{(dt\_emendas[, }\FunctionTok{unique}\NormalTok{(id\_municipio)]),}
  \StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Quantidade de municípios a receberem emendas individuais: "}\NormalTok{, }\FunctionTok{length}\NormalTok{(dt\_emendas[tipo\_emenda }\SpecialCharTok{==} \StringTok{"individual"}\NormalTok{, }\FunctionTok{unique}\NormalTok{(id\_municipio)]),}
  \StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Quantidade de municípios a receberem emendas de bancada: "}\NormalTok{, }\FunctionTok{length}\NormalTok{(dt\_emendas[tipo\_emenda }\SpecialCharTok{==} \StringTok{"bancada"}\NormalTok{, }\FunctionTok{unique}\NormalTok{(id\_municipio)]),}
  \StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Quantidade de municípios a receberem emendas de relator: "}\NormalTok{, }\FunctionTok{length}\NormalTok{(dt\_emendas[tipo\_emenda }\SpecialCharTok{==} \StringTok{"relator"}\NormalTok{, }\FunctionTok{unique}\NormalTok{(id\_municipio)])}
\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Quantidade de municípios a receberem qualquer tipo de emenda: 666
Quantidade de municípios a receberem emendas individuais: 633
Quantidade de municípios a receberem emendas de bancada: 66
Quantidade de municípios a receberem emendas de relator: 1
\end{verbatim}

\begin{itemize}
\tightlist
\item
  Note que 666 municípios brasileiros foram favorecidos por algum
  empenho de emenda em 2021 e que essas emendas foram somente
  individuais, de bancada ou de relator.
\end{itemize}

\subsection{1.2) Junção de dados}\label{junuxe7uxe3o-de-dados}

\subsubsection{1.2.1) Juntar bases de municípios e
eleições}\label{juntar-bases-de-municuxedpios-e-eleiuxe7uxf5es}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Ver se algum município de dt\_eleicoes não está em dt\_municípios}
\NormalTok{municipios\_dt\_eleicoes }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(dt\_eleicoes[, }\FunctionTok{paste0}\NormalTok{(id\_municipio\_nome, sigla\_uf)])}
\NormalTok{municipios\_dt\_municipios }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(dt\_municipios[, }\FunctionTok{paste0}\NormalTok{(id\_municipio\_nome, sigla\_uf)])}
\ControlFlowTok{for}\NormalTok{ (muni }\ControlFlowTok{in}\NormalTok{ municipios\_dt\_eleicoes) \{}
  \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\NormalTok{muni }\SpecialCharTok{\%in\%}\NormalTok{ municipios\_dt\_municipios) \{}
    \FunctionTok{print}\NormalTok{(muni)}
\NormalTok{  \}}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] "Lauro MullerSC"
[1] "Santa TeresinhaBA"
[1] "Grão ParáSC"
[1] "São Thomé das LetrasMG"
[1] "WestfaliaRS"
[1] "Vespasiano CorreaRS"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{rm}\NormalTok{(municipios\_dt\_eleicoes, municipios\_dt\_municipios, muni)}

\CommentTok{\# Renomear municípios de dt\_municipios fora do padrão de dt\_eleicoes}
\NormalTok{dt\_municipios[id\_municipio\_nome }\SpecialCharTok{==} \StringTok{"Lauro Müller"} \SpecialCharTok{\&}\NormalTok{ sigla\_uf }\SpecialCharTok{==} \StringTok{"SC"}\NormalTok{,}
\NormalTok{              id\_municipio\_nome }\SpecialCharTok{:}\ErrorTok{=} \StringTok{"Lauro Muller"}\NormalTok{]}
\NormalTok{dt\_municipios[id\_municipio\_nome }\SpecialCharTok{==} \StringTok{"Santa Terezinha"} \SpecialCharTok{\&}\NormalTok{ sigla\_uf }\SpecialCharTok{==} \StringTok{"BA"}\NormalTok{,}
\NormalTok{              id\_municipio\_nome }\SpecialCharTok{:}\ErrorTok{=} \StringTok{"Santa Teresinha"}\NormalTok{]}
\NormalTok{dt\_municipios[id\_municipio\_nome }\SpecialCharTok{==} \StringTok{"Grão{-}Pará"} \SpecialCharTok{\&}\NormalTok{ sigla\_uf }\SpecialCharTok{==} \StringTok{"SC"}\NormalTok{,}
\NormalTok{              id\_municipio\_nome }\SpecialCharTok{:}\ErrorTok{=} \StringTok{"Grão Pará"}\NormalTok{]}
\NormalTok{dt\_municipios[id\_municipio\_nome }\SpecialCharTok{==} \StringTok{"São Tomé das Letras"} \SpecialCharTok{\&}\NormalTok{ sigla\_uf }\SpecialCharTok{==} \StringTok{"MG"}\NormalTok{,}
\NormalTok{              id\_municipio\_nome }\SpecialCharTok{:}\ErrorTok{=} \StringTok{"São Thomé das Letras"}\NormalTok{]}
\NormalTok{dt\_municipios[id\_municipio\_nome }\SpecialCharTok{==} \StringTok{"Westfália"} \SpecialCharTok{\&}\NormalTok{ sigla\_uf }\SpecialCharTok{==} \StringTok{"RS"}\NormalTok{,}
\NormalTok{              id\_municipio\_nome }\SpecialCharTok{:}\ErrorTok{=} \StringTok{"Westfalia"}\NormalTok{]}
\NormalTok{dt\_municipios[id\_municipio\_nome }\SpecialCharTok{==} \StringTok{"Vespasiano Corrêa"} \SpecialCharTok{\&}\NormalTok{ sigla\_uf }\SpecialCharTok{==} \StringTok{"RS"}\NormalTok{,}
\NormalTok{              id\_municipio\_nome }\SpecialCharTok{:}\ErrorTok{=} \StringTok{"Vespasiano Correa"}\NormalTok{]}

\CommentTok{\# Repetir procedimento para ver se deu certo}
\NormalTok{municipios\_dt\_eleicoes }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(dt\_eleicoes[, }\FunctionTok{paste0}\NormalTok{(id\_municipio\_nome, sigla\_uf)])}
\NormalTok{municipios\_dt\_municipios }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(dt\_municipios[, }\FunctionTok{paste0}\NormalTok{(id\_municipio\_nome, sigla\_uf)])}
\ControlFlowTok{for}\NormalTok{ (muni }\ControlFlowTok{in}\NormalTok{ municipios\_dt\_eleicoes) \{}
  \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\NormalTok{muni }\SpecialCharTok{\%in\%}\NormalTok{ municipios\_dt\_municipios) \{}
    \FunctionTok{print}\NormalTok{(muni)}
\NormalTok{  \}}
\NormalTok{\}}
\FunctionTok{rm}\NormalTok{(municipios\_dt\_eleicoes, municipios\_dt\_municipios, muni)}

\CommentTok{\# Adicionar dados sobre os municípios com eleições de interesse}
\NormalTok{dt\_municipios\_eleicoes }\OtherTok{\textless{}{-}} \FunctionTok{merge}\NormalTok{(dt\_eleicoes, dt\_municipios, }\AttributeTok{all.x =}\NormalTok{ T)}

\CommentTok{\# Dar uma olhada na base de dados resultante}
\FunctionTok{str}\NormalTok{(dt\_municipios\_eleicoes)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Classes 'data.table' and 'data.frame':  487 obs. of  13 variables:
 $ id_municipio_nome      : chr  "Abel Figueiredo" "Acrelândia" "Acreúna" "Adelândia" ...
 $ sigla_uf               : chr  "PA" "AC" "GO" "GO" ...
 $ id_municipio           : chr  "1500131" "1200013" "5200134" "5200159" ...
 $ vitoria_pp             : num  0 0 1 0 0 1 1 0 0 1 ...
 $ votos_razao_pp         : num  0.491 0.477 0.502 0.464 0.482 ...
 $ votos_razao_pp_centr   : num  -0.00885 -0.0231 0.00169 -0.03585 -0.01821 ...
 $ votos_razao_pp_centr_sq: num  7.83e-05 5.34e-04 2.85e-06 1.29e-03 3.32e-04 ...
 $ mortalidade_infantil   : num  NA NA 7.52 NA 5.46 ...
 $ PIBpc                  : num  13999 25363 46316 19401 40864 ...
 $ taxa_escolarizacao     : num  0.997 0.961 0.982 1 1 ...
 $ pop                    : num  6136 14021 21568 2297 16041 ...
 $ densidade_demografica  : num  9.99 7.74 13.77 19.91 30 ...
 $ regiao                 : chr  "Norte" "Norte" "Centro-Oeste" "Centro-Oeste" ...
 - attr(*, ".internal.selfref")=<externalptr> 
 - attr(*, "sorted")= chr [1:2] "id_municipio_nome" "sigla_uf"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Verificar se houve algum NA}
\FunctionTok{colSums}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(dt\_municipios\_eleicoes))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
      id_municipio_nome                sigla_uf            id_municipio 
                      0                       0                       0 
             vitoria_pp          votos_razao_pp    votos_razao_pp_centr 
                      0                       0                       0 
votos_razao_pp_centr_sq    mortalidade_infantil                   PIBpc 
                      0                     171                       0 
     taxa_escolarizacao                     pop   densidade_demografica 
                      0                       0                       0 
                 regiao 
                      0 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Remover dts intermediárias}
\FunctionTok{rm}\NormalTok{(dt\_eleicoes, dt\_municipios)}
\end{Highlighting}
\end{Shaded}

\subsubsection{1.2.2) Juntar base de municípios e eleições com bases de
emendas}\label{juntar-base-de-municuxedpios-e-eleiuxe7uxf5es-com-bases-de-emendas}

\paragraph{1.2.2.1) Para emendas de todos os
tipos}\label{para-emendas-de-todos-os-tipos}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Resumir emendas por id\_municipio, independentemente de tipo}
\NormalTok{dt\_emendas\_todas }\OtherTok{\textless{}{-}}\NormalTok{ dt\_emendas[,}
\NormalTok{                               .(}\AttributeTok{valor\_empenhado\_ipca =} \FunctionTok{sum}\NormalTok{(valor\_empenhado\_ipca)),}
\NormalTok{                               by }\OtherTok{=}\NormalTok{ id\_municipio]}

\CommentTok{\# Adicionar dados sobre emendas ao dt\_municipios\_eleicoes}
\NormalTok{dt\_todas }\OtherTok{\textless{}{-}} \FunctionTok{merge}\NormalTok{(dt\_municipios\_eleicoes, dt\_emendas\_todas, }\AttributeTok{all.x =}\NormalTok{ T, }\AttributeTok{by =} \StringTok{"id\_municipio"}\NormalTok{)}

\CommentTok{\# Transformar NAs em 0}
\NormalTok{dt\_todas[}\FunctionTok{is.na}\NormalTok{(valor\_empenhado\_ipca), valor\_empenhado\_ipca }\SpecialCharTok{:}\ErrorTok{=} \DecValTok{0}\NormalTok{]}

\CommentTok{\# Adicionar coluna de valor empenhado per capita (usando valor de 2021 e pop de 2022)}
\NormalTok{dt\_todas[, valor\_empenhado\_ipca\_pc }\SpecialCharTok{:}\ErrorTok{=}\NormalTok{ valor\_empenhado\_ipca}\SpecialCharTok{/}\NormalTok{pop]}

\CommentTok{\# Ver quantos municípios com eleições acirradas receberam emendas}
\FunctionTok{writeLines}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}
  \StringTok{"Quantidade de municípios com eleições acirradas que receberam emendas: "}\NormalTok{,}
  \FunctionTok{nrow}\NormalTok{(dt\_todas[}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(valor\_empenhado\_ipca)])}
\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Quantidade de municípios com eleições acirradas que receberam emendas: 487
\end{verbatim}

\paragraph{1.2.2.2) Para emendas
individuais}\label{para-emendas-individuais}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Filtrar por somente emendas individuais}
\NormalTok{dt\_emendas\_individuais }\OtherTok{\textless{}{-}}\NormalTok{ dt\_emendas[tipo\_emenda }\SpecialCharTok{==} \StringTok{"individual"}\NormalTok{]}
\CommentTok{\# Remover coluna de tipo}
\NormalTok{dt\_emendas\_individuais[, tipo\_emenda }\SpecialCharTok{:}\ErrorTok{=} \ConstantTok{NULL}\NormalTok{]}

\CommentTok{\# Adicionar dados sobre emendas ao dt\_municipios\_eleicoes}
\NormalTok{dt\_individuais }\OtherTok{\textless{}{-}} \FunctionTok{merge}\NormalTok{(dt\_municipios\_eleicoes, dt\_emendas\_individuais, }\AttributeTok{all.x =}\NormalTok{ T, }\AttributeTok{by =} \StringTok{"id\_municipio"}\NormalTok{)}

\CommentTok{\# Transformar NAs em 0}
\NormalTok{dt\_individuais[}\FunctionTok{is.na}\NormalTok{(valor\_empenhado\_ipca), valor\_empenhado\_ipca }\SpecialCharTok{:}\ErrorTok{=} \DecValTok{0}\NormalTok{]}

\CommentTok{\# Adicionar coluna de valor empenhado per capita (usando valor de 2021 e pop de 2022)}
\NormalTok{dt\_individuais[, valor\_empenhado\_ipca\_pc }\SpecialCharTok{:}\ErrorTok{=}\NormalTok{ valor\_empenhado\_ipca}\SpecialCharTok{/}\NormalTok{pop]}

\CommentTok{\# Ver quantos municípios com eleições acirradas receberam emendas}
\FunctionTok{writeLines}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}
  \StringTok{"Quantidade de municípios com eleições acirradas que receberam emendas individuais: "}\NormalTok{,}
  \FunctionTok{nrow}\NormalTok{(dt\_individuais[}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(valor\_empenhado\_ipca)])}
\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Quantidade de municípios com eleições acirradas que receberam emendas individuais: 487
\end{verbatim}

\paragraph{1.2.2.3) Para emendas de
bancada}\label{para-emendas-de-bancada}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Filtrar por somente emendas de bancada}
\NormalTok{dt\_emendas\_bancada }\OtherTok{\textless{}{-}}\NormalTok{ dt\_emendas[tipo\_emenda }\SpecialCharTok{==} \StringTok{"bancada"}\NormalTok{]}
\CommentTok{\# Remover coluna de tipo}
\NormalTok{dt\_emendas\_bancada[, tipo\_emenda }\SpecialCharTok{:}\ErrorTok{=} \ConstantTok{NULL}\NormalTok{]}

\CommentTok{\# Adicionar dados sobre emendas ao dt\_municipios\_eleicoes}
\NormalTok{dt\_bancada }\OtherTok{\textless{}{-}} \FunctionTok{merge}\NormalTok{(dt\_municipios\_eleicoes, dt\_emendas\_bancada, }\AttributeTok{all.x =}\NormalTok{ T, }\AttributeTok{by =} \StringTok{"id\_municipio"}\NormalTok{)}

\CommentTok{\# Transformar NAs em 0}
\NormalTok{dt\_bancada[}\FunctionTok{is.na}\NormalTok{(valor\_empenhado\_ipca), valor\_empenhado\_ipca }\SpecialCharTok{:}\ErrorTok{=} \DecValTok{0}\NormalTok{]}

\CommentTok{\# Adicionar coluna de valor empenhado per capita (usando valor de 2021 e pop de 2022)}
\NormalTok{dt\_bancada[, valor\_empenhado\_ipca\_pc }\SpecialCharTok{:}\ErrorTok{=}\NormalTok{ valor\_empenhado\_ipca}\SpecialCharTok{/}\NormalTok{pop]}

\CommentTok{\# Ver quantos municípios com eleições acirradas receberam emendas}
\FunctionTok{writeLines}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}
  \StringTok{"Quantidade de municípios com eleições acirradas que receberam emendas de bancada: "}\NormalTok{,}
  \FunctionTok{nrow}\NormalTok{(dt\_bancada[}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(valor\_empenhado\_ipca)])}
\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Quantidade de municípios com eleições acirradas que receberam emendas de bancada: 487
\end{verbatim}

\paragraph{1.2.2.4) Para emendas de
relator}\label{para-emendas-de-relator}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Filtrar por somente emendas de relator}
\NormalTok{dt\_emendas\_relator }\OtherTok{\textless{}{-}}\NormalTok{ dt\_emendas[tipo\_emenda }\SpecialCharTok{==} \StringTok{"relator"}\NormalTok{]}
\CommentTok{\# Remover coluna de tipo}
\NormalTok{dt\_emendas\_relator[, tipo\_emenda }\SpecialCharTok{:}\ErrorTok{=} \ConstantTok{NULL}\NormalTok{]}

\CommentTok{\# Adicionar dados sobre emendas ao dt\_municipios\_eleicoes}
\NormalTok{dt\_relator }\OtherTok{\textless{}{-}} \FunctionTok{merge}\NormalTok{(dt\_municipios\_eleicoes, dt\_emendas\_relator, }\AttributeTok{all.x =}\NormalTok{ T, }\AttributeTok{by =} \StringTok{"id\_municipio"}\NormalTok{)}

\CommentTok{\# Adicionar coluna de valor empenhado per capita (usando valor de 2021 e pop de 2022)}
\NormalTok{dt\_relator[, valor\_empenhado\_ipca\_pc }\SpecialCharTok{:}\ErrorTok{=}\NormalTok{ valor\_empenhado\_ipca}\SpecialCharTok{/}\NormalTok{pop]}

\CommentTok{\# Ver quantos municípios com eleições acirradas receberam emendas}
\FunctionTok{writeLines}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(}
  \StringTok{"Quantidade de municípios com eleições acirradas que receberam emendas de relator: "}\NormalTok{,}
  \FunctionTok{nrow}\NormalTok{(dt\_relator[}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(valor\_empenhado\_ipca)])}
\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Quantidade de municípios com eleições acirradas que receberam emendas de relator: 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Transformar NAs em 0}
\NormalTok{dt\_relator[}\FunctionTok{is.na}\NormalTok{(valor\_empenhado\_ipca), valor\_empenhado\_ipca }\SpecialCharTok{:}\ErrorTok{=} \DecValTok{0}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  Note que nenhum município com eleições acirradas recebeu emendas de
  relator, então vamos analisar somente emendas individuais e de
  bancada.
\end{itemize}

\section{2) Estatísticas descritivas}\label{estatuxedsticas-descritivas}

Agora, vamos mostrar que os municípios em que o candidato do PP ganhou
vs.~perdeu por pouco de fato são semelhantes.

\subsection{2.1) Comparação de médias das características
municipais}\label{comparauxe7uxe3o-de-muxe9dias-das-caracteruxedsticas-municipais}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Criar dt com médias}
\NormalTok{medias\_municipios\_eleicoes }\OtherTok{\textless{}{-}}\NormalTok{ dt\_municipios\_eleicoes[}
\NormalTok{  ,}
\NormalTok{  .(}
    \AttributeTok{media\_pop =} \FunctionTok{mean}\NormalTok{(pop),}
    \AttributeTok{media\_densidade\_demografica =} \FunctionTok{mean}\NormalTok{(densidade\_demografica),}
    \AttributeTok{media\_PIBpc =} \FunctionTok{mean}\NormalTok{(PIBpc),}
    \AttributeTok{media\_taxa\_escolarizacao =} \FunctionTok{mean}\NormalTok{(taxa\_escolarizacao),}
    \AttributeTok{media\_mortalidade\_infantil =} \FunctionTok{mean}\NormalTok{(mortalidade\_infantil, }\AttributeTok{na.rm =}\NormalTok{ T)}
\NormalTok{  ),}
\NormalTok{  by }\OtherTok{=}\NormalTok{ vitoria\_pp}
\NormalTok{]}

\CommentTok{\# Plotar médias de quem venceu vs. não venceu {-} formatar}
\NormalTok{titulo }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Comparação das médias de características municipais"}\NormalTok{, }\AttributeTok{subtitle =} \StringTok{"Fontes dos dados: TSE, IBGE (2021, 2022). Elaboração própria."}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}

\NormalTok{g1 }\OtherTok{\textless{}{-}}\NormalTok{ medias\_municipios\_eleicoes }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ media\_pop, }\AttributeTok{x =} \FunctionTok{as.factor}\NormalTok{(vitoria\_pp))) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{""}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"População"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Prefeito do PP?"}\NormalTok{)}

\NormalTok{g2 }\OtherTok{\textless{}{-}}\NormalTok{ medias\_municipios\_eleicoes }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ media\_densidade\_demografica, }\AttributeTok{x =} \FunctionTok{as.factor}\NormalTok{(vitoria\_pp))) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{""}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Densidade demográfica"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Prefeito do PP?"}\NormalTok{)}

\NormalTok{g3 }\OtherTok{\textless{}{-}}\NormalTok{ medias\_municipios\_eleicoes }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ media\_PIBpc, }\AttributeTok{x =} \FunctionTok{as.factor}\NormalTok{(vitoria\_pp))) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{""}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"PIB per capita"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Prefeito do PP?"}\NormalTok{)}

\NormalTok{g4 }\OtherTok{\textless{}{-}}\NormalTok{ medias\_municipios\_eleicoes }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ media\_taxa\_escolarizacao, }\AttributeTok{x =} \FunctionTok{as.factor}\NormalTok{(vitoria\_pp))) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{""}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Taxa de escolarização"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Prefeito do PP?"}\NormalTok{)}

\NormalTok{g5 }\OtherTok{\textless{}{-}}\NormalTok{ medias\_municipios\_eleicoes }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ media\_mortalidade\_infantil, }\AttributeTok{x =} \FunctionTok{as.factor}\NormalTok{(vitoria\_pp))) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{""}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Mortalidade infantil"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Prefeito do PP?"}\NormalTok{)}

\NormalTok{graficos }\OtherTok{\textless{}{-}} \FunctionTok{plot\_grid}\NormalTok{(g1, g2, g3, g4, g5)}

\FunctionTok{plot\_grid}\NormalTok{(titulo, graficos, }\AttributeTok{ncol =} \DecValTok{1}\NormalTok{, }\AttributeTok{rel\_heights =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.15}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{01_estimacao_principal_brasil_20251121_files/figure-pdf/unnamed-chunk-11-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Mostrar quais diferenças são estatisticamente significantes {-} fazer teste de comparação des}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  As médias de população e densidade demográfica são bastante diferentes
  entre os dois grupos. Vamos olhar para a mediana, que reduz o efeito
  de outliers:
\end{itemize}

\subsection{2.2) Comparação de medianas das características
municipais}\label{comparauxe7uxe3o-de-medianas-das-caracteruxedsticas-municipais}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Criar dt com medianas}
\NormalTok{medianas\_municipios\_eleicoes }\OtherTok{\textless{}{-}}\NormalTok{ dt\_municipios\_eleicoes[}
\NormalTok{  ,}
\NormalTok{  .(}
    \AttributeTok{mediana\_pop =} \FunctionTok{median}\NormalTok{(pop),}
    \AttributeTok{mediana\_densidade\_demografica =} \FunctionTok{median}\NormalTok{(densidade\_demografica),}
    \AttributeTok{mediana\_PIBpc =} \FunctionTok{median}\NormalTok{(PIBpc),}
    \AttributeTok{mediana\_taxa\_escolarizacao =} \FunctionTok{median}\NormalTok{(taxa\_escolarizacao),}
    \AttributeTok{mediana\_mortalidade\_infantil =} \FunctionTok{median}\NormalTok{(mortalidade\_infantil, }\AttributeTok{na.rm =}\NormalTok{ T)}
\NormalTok{  ),}
\NormalTok{  by }\OtherTok{=}\NormalTok{ vitoria\_pp}
\NormalTok{]}

\CommentTok{\# Plotar medianas de quem venceu vs. não venceu {-} formatar}
\NormalTok{titulo }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Comparação das medianas de características municipais"}\NormalTok{, }\AttributeTok{subtitle =} \StringTok{"Fontes dos dados: TSE (2021), IBGE (2021, 2022). Elaboração própria."}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{theme\_minimal}\NormalTok{()}

\NormalTok{g1 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ mediana\_pop, }\AttributeTok{x =} \FunctionTok{as.factor}\NormalTok{(vitoria\_pp)), }\AttributeTok{data =}\NormalTok{ medianas\_municipios\_eleicoes) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{""}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"População"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Prefeito do PP?"}\NormalTok{)}

\NormalTok{g2 }\OtherTok{\textless{}{-}}\NormalTok{ medianas\_municipios\_eleicoes }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ mediana\_densidade\_demografica, }\AttributeTok{x =} \FunctionTok{as.factor}\NormalTok{(vitoria\_pp))) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{""}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Densidade demográfica"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Prefeito do PP?"}\NormalTok{)}

\NormalTok{g3 }\OtherTok{\textless{}{-}}\NormalTok{ medianas\_municipios\_eleicoes }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ mediana\_PIBpc, }\AttributeTok{x =} \FunctionTok{as.factor}\NormalTok{(vitoria\_pp))) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{""}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"PIB per capita"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Prefeito do PP?"}\NormalTok{)}

\NormalTok{g4 }\OtherTok{\textless{}{-}}\NormalTok{ medianas\_municipios\_eleicoes }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ mediana\_taxa\_escolarizacao, }\AttributeTok{x =} \FunctionTok{as.factor}\NormalTok{(vitoria\_pp))) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{""}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Taxa de escolarização"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Prefeito do PP?"}\NormalTok{)}

\NormalTok{g5 }\OtherTok{\textless{}{-}}\NormalTok{ medianas\_municipios\_eleicoes }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ mediana\_mortalidade\_infantil, }\AttributeTok{x =} \FunctionTok{as.factor}\NormalTok{(vitoria\_pp))) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{""}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Mortalidade infantil"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Prefeito do PP?"}\NormalTok{)}

\NormalTok{graficos }\OtherTok{\textless{}{-}} \FunctionTok{plot\_grid}\NormalTok{(g1, g2, g3, g4, g5)}

\FunctionTok{plot\_grid}\NormalTok{(titulo, graficos, }\AttributeTok{ncol =} \DecValTok{1}\NormalTok{, }\AttributeTok{rel\_heights =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.15}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{01_estimacao_principal_brasil_20251121_files/figure-pdf/unnamed-chunk-12-1.pdf}

\begin{itemize}
\tightlist
\item
  Usando a mediana, as médias de população e densidade demográfica
  ficaram bem mais parecidas, mas as de mortalidade infantil, um pouco
  menos.
\end{itemize}

\subsection{2.4) Valores empenhados via emendas
parlamentares}\label{valores-empenhados-via-emendas-parlamentares}

Vamos plotar a média dos valores empenhados per capita dos municípios
que tiveram eleições acirradas e elegeram ou não o candidato do PP, o
que seria equivalente a visualizar o modelo mais simples de RDD.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Criar dts com médias}
\NormalTok{media\_empenho\_total }\OtherTok{\textless{}{-}}\NormalTok{ dt\_todas[}
\NormalTok{  ,}
\NormalTok{  .(}\AttributeTok{media\_empenho =} \FunctionTok{mean}\NormalTok{(valor\_empenhado\_ipca\_pc)),}
\NormalTok{  by }\OtherTok{=}\NormalTok{ vitoria\_pp}
\NormalTok{]}
\NormalTok{media\_empenho\_individuais }\OtherTok{\textless{}{-}}\NormalTok{ dt\_individuais[}
\NormalTok{  ,}
\NormalTok{  .(}\AttributeTok{media\_empenho =} \FunctionTok{mean}\NormalTok{(valor\_empenhado\_ipca\_pc)),}
\NormalTok{  by }\OtherTok{=}\NormalTok{ vitoria\_pp}
\NormalTok{]}
\NormalTok{media\_empenho\_bancada }\OtherTok{\textless{}{-}}\NormalTok{ dt\_bancada[}
\NormalTok{  ,}
\NormalTok{  .(}\AttributeTok{media\_empenho =} \FunctionTok{mean}\NormalTok{(valor\_empenhado\_ipca\_pc)),}
\NormalTok{  by }\OtherTok{=}\NormalTok{ vitoria\_pp}
\NormalTok{]}

\CommentTok{\# Plotar diferença em valores empenhados pelo resultado da eleição}
\NormalTok{titulo }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Comparação de médias de valor empenhado per capita municipal"}\NormalTok{, }\AttributeTok{subtitle =} \StringTok{"Fontes dos dados: TSE (2021), SIGA Brasil (2021). Elaboração própria."}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{theme\_minimal}\NormalTok{()}

\NormalTok{g1 }\OtherTok{\textless{}{-}}\NormalTok{ media\_empenho\_total }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ media\_empenho, }\AttributeTok{x =} \FunctionTok{as.factor}\NormalTok{(vitoria\_pp))) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{labels =} \FunctionTok{label\_currency}\NormalTok{(}\AttributeTok{prefix =} \StringTok{"R$ "}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{""}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Todas as EPs"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Prefeito do PP?"}\NormalTok{)}

\NormalTok{g2 }\OtherTok{\textless{}{-}}\NormalTok{ media\_empenho\_individuais }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ media\_empenho, }\AttributeTok{x =} \FunctionTok{as.factor}\NormalTok{(vitoria\_pp))) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{labels =} \FunctionTok{label\_currency}\NormalTok{(}\AttributeTok{prefix =} \StringTok{"R$ "}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{""}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"EPs individuais"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Prefeito do PP?"}\NormalTok{)}

\NormalTok{g3 }\OtherTok{\textless{}{-}}\NormalTok{ media\_empenho\_bancada }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ media\_empenho, }\AttributeTok{x =} \FunctionTok{as.factor}\NormalTok{(vitoria\_pp))) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{labels =} \FunctionTok{label\_currency}\NormalTok{(}\AttributeTok{prefix =} \StringTok{"R$ "}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{""}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"EPs de bancada"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Prefeito do PP?"}\NormalTok{)}

\NormalTok{graficos }\OtherTok{\textless{}{-}} \FunctionTok{plot\_grid}\NormalTok{(g1, g2, g3)}

\FunctionTok{plot\_grid}\NormalTok{(titulo, graficos, }\AttributeTok{ncol =} \DecValTok{1}\NormalTok{, }\AttributeTok{rel\_heights =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.15}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{01_estimacao_principal_brasil_20251121_files/figure-pdf/unnamed-chunk-13-1.pdf}

\section{3) Estimação}\label{estimauxe7uxe3o}

Vamos estimar o valor adicional recebido via emendas parlamentares pelos
municípios em que o candidato a prefeito do PP ganhou por pouco, usando
alguns modelos diferentes.

\begin{itemize}
\tightlist
\item
  Note que, quando o modelo inclui a running variable, é sua versão
  centralizada (votos\_razao\_pp\_centr), porque isso evita que o
  intercepto tenha valores sem sentido (como valores empenhados
  negativos).
\end{itemize}

\subsection{3.1) Para todas as emendas}\label{para-todas-as-emendas}

\subsubsection{3.1.1) Valores absolutos}\label{valores-absolutos}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Duas regressões lineares com controle de razão de votos do PP}
\NormalTok{regs\_lineares }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr, }\AttributeTok{data =}\NormalTok{ dt\_todas)}

\CommentTok{\# Duas regressões com linearidade flexibilizada e controle de razão de votos do PP}
\NormalTok{regs\_flexiveis }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr }\SpecialCharTok{+}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr\_sq, }\AttributeTok{data =}\NormalTok{ dt\_todas)}

\CommentTok{\# Duas regressões lineares com controles}
\NormalTok{regs\_lineares\_controles }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr }\SpecialCharTok{+}\NormalTok{ regiao }\SpecialCharTok{+}\NormalTok{ pop }\SpecialCharTok{+}\NormalTok{ PIBpc }\SpecialCharTok{+}\NormalTok{ taxa\_escolarizacao }\SpecialCharTok{+}\NormalTok{ mortalidade\_infantil, }\AttributeTok{data =}\NormalTok{ dt\_todas)}

\CommentTok{\# Duas regressões com linearidade flexibilizada e controles}
\NormalTok{regs\_flexiveis\_controles }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr }\SpecialCharTok{+}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr\_sq }\SpecialCharTok{+}\NormalTok{ regiao }\SpecialCharTok{+}\NormalTok{ pop }\SpecialCharTok{+}\NormalTok{ PIBpc }\SpecialCharTok{+}\NormalTok{ taxa\_escolarizacao }\SpecialCharTok{+}\NormalTok{ mortalidade\_infantil, }\AttributeTok{data =}\NormalTok{ dt\_todas)}

\CommentTok{\# Resultados}
\FunctionTok{modelsummary}\NormalTok{(}\FunctionTok{list}\NormalTok{(}
  \StringTok{"Duas regressões lineares"} \OtherTok{=}\NormalTok{ regs\_lineares,}
  \StringTok{"Duas regressões não lineares"} \OtherTok{=}\NormalTok{ regs\_flexiveis,}
  \StringTok{"Duas regressões lineares com controles"} \OtherTok{=}\NormalTok{ regs\_lineares\_controles,}
  \StringTok{"Duas regressões não lineares com controles"} \OtherTok{=}\NormalTok{ regs\_flexiveis\_controles}
\NormalTok{),}
\AttributeTok{statistic =} \StringTok{"p.value"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Warning in attr(.knitEnv$meta, "knit_meta_id"): 'xfun::attr()' is deprecated.
Use 'xfun::attr2()' instead.
See help("Deprecated")
Warning in attr(.knitEnv$meta, "knit_meta_id"): 'xfun::attr()' is deprecated.
Use 'xfun::attr2()' instead.
See help("Deprecated")
\end{verbatim}

\begin{table}
\centering
\begin{tblr}[         %% tabularray outer open
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]Q[]Q[]Q[]},
column{1}={halign=l,},
column{2}={halign=c,},
column{3}={halign=c,},
column{4}={halign=c,},
column{5}={halign=c,},
hline{30}={1,2,3,4,5}{solid, 0.05em, black},
}                     %% tabularray inner close
\toprule
& Duas regressões lineares & Duas regressões não lineares & Duas regressões lineares com controles & Duas regressões não lineares com controles \\ \midrule %% TinyTableHeader
(Intercept)                                    & \num{-151212.101}   & \num{119659.873}      & \num{1232066.679}  & \num{1.818234e+06}  \\
& (\num{0.465})       & (\num{0.507})         & (\num{0.760})      & (\num{0.636})       \\
vitoria\_pp                                   & \num{390887.808}    & \num{-180420.658}     & \num{23974.242}    & \num{-8.268956e+05} \\
& (\num{0.153})       & (\num{0.473})         & (\num{0.922})      & (\num{0.039})       \\
votos\_razao\_pp\_centr                     & \num{-13758155.684} & \num{16608177.685}    & \num{-2298470.713} & \num{5.754277e+07}  \\
& (\num{0.293})       & (\num{0.579})         & (\num{0.665})      & (\num{0.168})       \\
vitoria\_pp × votos\_razao\_pp\_centr      & \num{21802773.065}  & \num{37127257.651}    & \num{9433568.706}  & \num{-3.045684e+06} \\
& (\num{0.144})       & (\num{0.429})         & (\num{0.213})      & (\num{0.943})       \\
votos\_razao\_pp\_centr\_sq                &                      & \num{609045075.583}   &                     & \num{1.184003e+09}  \\
&                      & (\num{0.470})         &                     & (\num{0.140})       \\
vitoria\_pp × votos\_razao\_pp\_centr\_sq &                      & \num{-1589602583.149} &                     & \num{-2.191192e+09} \\
&                      & (\num{0.150})         &                     & (\num{0.080})       \\
regiaoNordeste                                 &                      &                        & \num{-1248521.214} & \num{-1.342048e+06} \\
&                      &                        & (\num{0.223})      & (\num{0.198})       \\
regiaoNorte                                    &                      &                        & \num{-585292.588}  & \num{-7.061342e+05} \\
&                      &                        & (\num{0.670})      & (\num{0.619})       \\
regiaoSudeste                                  &                      &                        & \num{-1223210.756} & \num{-1.309549e+06} \\
&                      &                        & (\num{0.239})      & (\num{0.214})       \\
regiaoSul                                      &                      &                        & \num{-1119612.863} & \num{-1.274387e+06} \\
&                      &                        & (\num{0.258})      & (\num{0.223})       \\
pop                                            &                      &                        & \num{49.594}       & \num{4.940100e+01}  \\
&                      &                        & (\num{<0.001})     & (\num{<0.001})      \\
PIBpc                                          &                      &                        & \num{-0.952}       & \num{-4.570000e-01} \\
&                      &                        & (\num{0.617})      & (\num{0.787})       \\
taxa\_escolarizacao                           &                      &                        & \num{-1399097.542} & \num{-1.319973e+06} \\
&                      &                        & (\num{0.728})      & (\num{0.725})       \\
mortalidade\_infantil                         &                      &                        & \num{21751.560}    & \num{2.013571e+04}  \\
&                      &                        & (\num{<0.001})     & (\num{0.002})       \\
Num.Obs.                                       & \num{487}           & \num{487}             & \num{316}          & \num{316}           \\
R2                                             & \num{0.005}         & \num{0.009}           & \num{0.730}        & \num{0.734}         \\
R2 Adj.                                        & \num{-0.002}        & \num{-0.001}          & \num{0.720}        & \num{0.722}         \\
AIC                                            & \num{15861.1}       & \num{15862.8}         & \num{10033.8}      & \num{10033.3}       \\
BIC                                            & \num{15882.0}       & \num{15892.1}         & \num{10082.6}      & \num{10089.6}       \\
RMSE                                           & \num{2828561.98}    & \num{2821978.91}      & \num{1823257.01}   & \num{1810389.33}    \\
\bottomrule
\end{tblr}
\end{table}

\subsubsection{\texorpdfstring{3.1.1) Valores \emph{per
capita}}{3.1.1) Valores per capita}}\label{valores-per-capita}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Duas regressões lineares com controle de razão de votos do PP}
\NormalTok{regs\_lineares }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca\_pc }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr, }\AttributeTok{data =}\NormalTok{ dt\_todas)}

\CommentTok{\# Duas regressões com linearidade flexibilizada e controle de razão de votos do PP}
\NormalTok{regs\_flexiveis }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca\_pc }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr }\SpecialCharTok{+}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr\_sq, }\AttributeTok{data =}\NormalTok{ dt\_todas)}

\CommentTok{\# Duas regressões lineares com controles}
\NormalTok{regs\_lineares\_controles }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca\_pc }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr }\SpecialCharTok{+}\NormalTok{ regiao }\SpecialCharTok{+}\NormalTok{ pop }\SpecialCharTok{+}\NormalTok{ PIBpc }\SpecialCharTok{+}\NormalTok{ taxa\_escolarizacao }\SpecialCharTok{+}\NormalTok{ mortalidade\_infantil, }\AttributeTok{data =}\NormalTok{ dt\_todas)}

\CommentTok{\# Duas regressões com linearidade flexibilizada e controles}
\NormalTok{regs\_flexiveis\_controles }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca\_pc }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr }\SpecialCharTok{+}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr\_sq }\SpecialCharTok{+}\NormalTok{ regiao }\SpecialCharTok{+}\NormalTok{ pop }\SpecialCharTok{+}\NormalTok{ PIBpc }\SpecialCharTok{+}\NormalTok{ taxa\_escolarizacao }\SpecialCharTok{+}\NormalTok{ mortalidade\_infantil, }\AttributeTok{data =}\NormalTok{ dt\_todas)}

\CommentTok{\# Resultados}
\FunctionTok{modelsummary}\NormalTok{(}\FunctionTok{list}\NormalTok{(}
  \StringTok{"Duas regressões lineares"} \OtherTok{=}\NormalTok{ regs\_lineares,}
  \StringTok{"Duas regressões não lineares"} \OtherTok{=}\NormalTok{ regs\_flexiveis,}
  \StringTok{"Duas regressões lineares com controles"} \OtherTok{=}\NormalTok{ regs\_lineares\_controles,}
  \StringTok{"Duas regressões não lineares com controles"} \OtherTok{=}\NormalTok{ regs\_flexiveis\_controles}
\NormalTok{),}
\AttributeTok{statistic =} \StringTok{"p.value"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Warning in attr(.knitEnv$meta, "knit_meta_id"): 'xfun::attr()' is deprecated.
Use 'xfun::attr2()' instead.
See help("Deprecated")
Warning in attr(.knitEnv$meta, "knit_meta_id"): 'xfun::attr()' is deprecated.
Use 'xfun::attr2()' instead.
See help("Deprecated")
\end{verbatim}

\begin{table}
\centering
\begin{tblr}[         %% tabularray outer open
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]Q[]Q[]Q[]},
column{1}={halign=l,},
column{2}={halign=c,},
column{3}={halign=c,},
column{4}={halign=c,},
column{5}={halign=c,},
hline{30}={1,2,3,4,5}{solid, 0.05em, black},
}                     %% tabularray inner close
\toprule
& Duas regressões lineares & Duas regressões não lineares & Duas regressões lineares com controles & Duas regressões não lineares com controles \\ \midrule %% TinyTableHeader
(Intercept)                                    & \num{3.473}    & \num{-8.716}     & \num{72.802}  & \num{50.919}     \\
& (\num{0.096})  & (\num{0.437})    & (\num{0.800}) & (\num{0.860})    \\
vitoria\_pp                                   & \num{0.960}    & \num{12.941}     & \num{-11.517} & \num{8.020}      \\
& (\num{0.764})  & (\num{0.266})    & (\num{0.220}) & (\num{0.607})    \\
votos\_razao\_pp\_centr                     & \num{-211.581} & \num{-1578.027}  & \num{47.855}  & \num{-1987.031}  \\
& (\num{0.395})  & (\num{0.283})    & (\num{0.776}) & (\num{0.355})    \\
vitoria\_pp × votos\_razao\_pp\_centr      & \num{179.586}  & \num{1577.749}   & \num{-35.184} & \num{1824.514}   \\
& (\num{0.491})  & (\num{0.290})    & (\num{0.867}) & (\num{0.261})    \\
votos\_razao\_pp\_centr\_sq                &                 & \num{-27406.237} &                & \num{-40236.567} \\
&                 & (\num{0.270})    &                & (\num{0.333})    \\
vitoria\_pp × votos\_razao\_pp\_centr\_sq &                 & \num{26725.552}  &                & \num{43893.830}  \\
&                 & (\num{0.290})    &                & (\num{0.421})    \\
regiaoNordeste                                 &                 &                   & \num{-0.458}  & \num{2.671}      \\
&                 &                   & (\num{0.951}) & (\num{0.772})    \\
regiaoNorte                                    &                 &                   & \num{98.433}  & \num{100.757}    \\
&                 &                   & (\num{0.293}) & (\num{0.294})    \\
regiaoSudeste                                  &                 &                   & \num{1.049}   & \num{3.889}      \\
&                 &                   & (\num{0.897}) & (\num{0.689})    \\
regiaoSul                                      &                 &                   & \num{-5.941}  & \num{-2.874}     \\
&                 &                   & (\num{0.400}) & (\num{0.730})    \\
pop                                            &                 &                   & \num{0.000}   & \num{0.000}      \\
&                 &                   & (\num{0.170}) & (\num{0.144})    \\
PIBpc                                          &                 &                   & \num{0.000}   & \num{0.000}      \\
&                 &                   & (\num{0.855}) & (\num{0.978})    \\
taxa\_escolarizacao                           &                 &                   & \num{-79.946} & \num{-80.023}    \\
&                 &                   & (\num{0.786}) & (\num{0.793})    \\
mortalidade\_infantil                         &                 &                   & \num{0.795}   & \num{0.820}      \\
&                 &                   & (\num{0.297}) & (\num{0.302})    \\
Num.Obs.                                       & \num{487}      & \num{487}        & \num{316}     & \num{316}        \\
R2                                             & \num{0.003}    & \num{0.006}      & \num{0.117}   & \num{0.121}      \\
R2 Adj.                                        & \num{-0.003}   & \num{-0.005}     & \num{0.085}   & \num{0.083}      \\
AIC                                            & \num{5364.9}   & \num{5367.5}     & \num{3589.0}  & \num{3591.5}     \\
BIC                                            & \num{5385.8}   & \num{5396.8}     & \num{3637.9}  & \num{3647.9}     \\
RMSE                                           & \num{59.08}    & \num{58.99}      & \num{67.95}   & \num{67.79}      \\
\bottomrule
\end{tblr}
\end{table}

\subsection{3.2) Para emendas
individuais}\label{para-emendas-individuais-1}

\subsubsection{3.2.1) Valores absolutos}\label{valores-absolutos-1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Duas regressões lineares com controle de razão de votos do PP}
\NormalTok{regs\_lineares }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr, }\AttributeTok{data =}\NormalTok{ dt\_individuais)}

\CommentTok{\# Duas regressões com linearidade flexibilizada e controle de razão de votos do PP}
\NormalTok{regs\_flexiveis }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr }\SpecialCharTok{+}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr\_sq, }\AttributeTok{data =}\NormalTok{ dt\_individuais)}

\CommentTok{\# Duas regressões lineares com controles}
\NormalTok{regs\_lineares\_controles }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr }\SpecialCharTok{+}\NormalTok{ regiao }\SpecialCharTok{+}\NormalTok{ pop }\SpecialCharTok{+}\NormalTok{ PIBpc }\SpecialCharTok{+}\NormalTok{ taxa\_escolarizacao }\SpecialCharTok{+}\NormalTok{ mortalidade\_infantil, }\AttributeTok{data =}\NormalTok{ dt\_individuais)}

\CommentTok{\# Duas regressões com linearidade flexibilizada e controles}
\NormalTok{regs\_flexiveis\_controles }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr }\SpecialCharTok{+}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr\_sq }\SpecialCharTok{+}\NormalTok{ regiao }\SpecialCharTok{+}\NormalTok{ pop }\SpecialCharTok{+}\NormalTok{ PIBpc }\SpecialCharTok{+}\NormalTok{ taxa\_escolarizacao }\SpecialCharTok{+}\NormalTok{ mortalidade\_infantil, }\AttributeTok{data =}\NormalTok{ dt\_individuais)}

\CommentTok{\# Resultados}
\FunctionTok{modelsummary}\NormalTok{(}\FunctionTok{list}\NormalTok{(}
  \StringTok{"Duas regressões lineares"} \OtherTok{=}\NormalTok{ regs\_lineares,}
  \StringTok{"Duas regressões não lineares"} \OtherTok{=}\NormalTok{ regs\_flexiveis,}
  \StringTok{"Duas regressões lineares com controles"} \OtherTok{=}\NormalTok{ regs\_lineares\_controles,}
  \StringTok{"Duas regressões não lineares com controles"} \OtherTok{=}\NormalTok{ regs\_flexiveis\_controles}
\NormalTok{),}
\AttributeTok{statistic =} \StringTok{"p.value"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Warning in attr(.knitEnv$meta, "knit_meta_id"): 'xfun::attr()' is deprecated.
Use 'xfun::attr2()' instead.
See help("Deprecated")
Warning in attr(.knitEnv$meta, "knit_meta_id"): 'xfun::attr()' is deprecated.
Use 'xfun::attr2()' instead.
See help("Deprecated")
\end{verbatim}

\begin{table}
\centering
\begin{tblr}[         %% tabularray outer open
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]Q[]Q[]Q[]},
column{1}={halign=l,},
column{2}={halign=c,},
column{3}={halign=c,},
column{4}={halign=c,},
column{5}={halign=c,},
hline{30}={1,2,3,4,5}{solid, 0.05em, black},
}                     %% tabularray inner close
\toprule
& Duas regressões lineares & Duas regressões não lineares & Duas regressões lineares com controles & Duas regressões não lineares com controles \\ \midrule %% TinyTableHeader
(Intercept)                                    & \num{44363.002}   & \num{44530.919}    & \num{-1939418.602} & \num{-1920995.216}  \\
& (\num{0.076})     & (\num{0.133})      & (\num{0.168})      & (\num{0.172})       \\
vitoria\_pp                                   & \num{-21036.253}  & \num{-12809.181}   & \num{-152952.781}  & \num{-112015.605}   \\
& (\num{0.731})     & (\num{0.794})      & (\num{0.175})      & (\num{0.311})       \\
votos\_razao\_pp\_centr                     & \num{110385.715}  & \num{129210.225}   & \num{3334618.733}  & \num{4113053.911}   \\
& (\num{0.909})     & (\num{0.965})      & (\num{0.157})      & (\num{0.682})       \\
vitoria\_pp × votos\_razao\_pp\_centr      & \num{3838198.743} & \num{2542652.110}  & \num{1180821.738}  & \num{-6925489.668}  \\
& (\num{0.370})     & (\num{0.721})      & (\num{0.803})      & (\num{0.615})       \\
votos\_razao\_pp\_centr\_sq                &                    & \num{377555.459}   &                     & \num{15262678.992}  \\
&                    & (\num{0.996})      &                     & (\num{0.944})       \\
vitoria\_pp × votos\_razao\_pp\_centr\_sq &                    & \num{27021810.960} &                     & \num{140947964.638} \\
&                    & (\num{0.881})      &                     & (\num{0.676})       \\
regiaoNordeste                                 &                    &                     & \num{41901.405}    & \num{40969.279}     \\
&                    &                     & (\num{0.737})      & (\num{0.750})       \\
regiaoNorte                                    &                    &                     & \num{-136512.674}  & \num{-128206.520}   \\
&                    &                     & (\num{0.622})      & (\num{0.642})       \\
regiaoSudeste                                  &                    &                     & \num{368291.152}   & \num{367696.621}    \\
&                    &                     & (\num{0.125})      & (\num{0.129})       \\
regiaoSul                                      &                    &                     & \num{75130.376}    & \num{85269.129}     \\
&                    &                     & (\num{0.526})      & (\num{0.498})       \\
pop                                            &                    &                     & \num{10.177}       & \num{10.204}        \\
&                    &                     & (\num{<0.001})     & (\num{<0.001})      \\
PIBpc                                          &                    &                     & \num{-0.532}       & \num{-0.667}        \\
&                    &                     & (\num{0.517})      & (\num{0.509})       \\
taxa\_escolarizacao                           &                    &                     & \num{1763916.320}  & \num{1750480.773}   \\
&                    &                     & (\num{0.210})      & (\num{0.212})       \\
mortalidade\_infantil                         &                    &                     & \num{3185.929}     & \num{3328.376}      \\
&                    &                     & (\num{0.031})      & (\num{0.036})       \\
Num.Obs.                                       & \num{487}         & \num{487}          & \num{316}          & \num{316}           \\
R2                                             & \num{0.006}       & \num{0.006}        & \num{0.459}        & \num{0.460}         \\
R2 Adj.                                        & \num{0.000}       & \num{-0.004}       & \num{0.439}        & \num{0.437}         \\
AIC                                            & \num{14551.8}     & \num{14555.8}      & \num{9403.3}       & \num{9406.8}        \\
BIC                                            & \num{14572.7}     & \num{14585.1}      & \num{9452.1}       & \num{9463.1}        \\
RMSE                                           & \num{737497.23}   & \num{737480.12}    & \num{672331.72}    & \num{671824.67}     \\
\bottomrule
\end{tblr}
\end{table}

\subsubsection{\texorpdfstring{3.2.2) Valores \emph{per
capita}}{3.2.2) Valores per capita}}\label{valores-per-capita-1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Duas regressões lineares com controle de razão de votos do PP}
\NormalTok{regs\_lineares }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca\_pc }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr, }\AttributeTok{data =}\NormalTok{ dt\_individuais)}

\CommentTok{\# Duas regressões com linearidade flexibilizada e controle de razão de votos do PP}
\NormalTok{regs\_flexiveis }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca\_pc }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr }\SpecialCharTok{+}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr\_sq, }\AttributeTok{data =}\NormalTok{ dt\_individuais)}

\CommentTok{\# Duas regressões lineares com controles}
\NormalTok{regs\_lineares\_controles }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca\_pc }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr }\SpecialCharTok{+}\NormalTok{ regiao }\SpecialCharTok{+}\NormalTok{ pop }\SpecialCharTok{+}\NormalTok{ PIBpc }\SpecialCharTok{+}\NormalTok{ taxa\_escolarizacao }\SpecialCharTok{+}\NormalTok{ mortalidade\_infantil, }\AttributeTok{data =}\NormalTok{ dt\_individuais)}

\CommentTok{\# Duas regressões com linearidade flexibilizada e controles}
\NormalTok{regs\_flexiveis\_controles }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca\_pc }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr }\SpecialCharTok{+}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr\_sq }\SpecialCharTok{+}\NormalTok{ regiao }\SpecialCharTok{+}\NormalTok{ pop }\SpecialCharTok{+}\NormalTok{ PIBpc }\SpecialCharTok{+}\NormalTok{ taxa\_escolarizacao }\SpecialCharTok{+}\NormalTok{ mortalidade\_infantil, }\AttributeTok{data =}\NormalTok{ dt\_individuais)}

\CommentTok{\# Resultados}
\FunctionTok{modelsummary}\NormalTok{(}\FunctionTok{list}\NormalTok{(}
  \StringTok{"Duas regressões lineares"} \OtherTok{=}\NormalTok{ regs\_lineares,}
  \StringTok{"Duas regressões não lineares"} \OtherTok{=}\NormalTok{ regs\_flexiveis,}
  \StringTok{"Duas regressões lineares com controles"} \OtherTok{=}\NormalTok{ regs\_lineares\_controles,}
  \StringTok{"Duas regressões não lineares com controles"} \OtherTok{=}\NormalTok{ regs\_flexiveis\_controles}
\NormalTok{),}
\AttributeTok{statistic =} \StringTok{"p.value"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Warning in attr(.knitEnv$meta, "knit_meta_id"): 'xfun::attr()' is deprecated.
Use 'xfun::attr2()' instead.
See help("Deprecated")
Warning in attr(.knitEnv$meta, "knit_meta_id"): 'xfun::attr()' is deprecated.
Use 'xfun::attr2()' instead.
See help("Deprecated")
\end{verbatim}

\begin{table}
\centering
\begin{tblr}[         %% tabularray outer open
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]Q[]Q[]Q[]},
column{1}={halign=l,},
column{2}={halign=c,},
column{3}={halign=c,},
column{4}={halign=c,},
column{5}={halign=c,},
hline{30}={1,2,3,4,5}{solid, 0.05em, black},
}                     %% tabularray inner close
\toprule
& Duas regressões lineares & Duas regressões não lineares & Duas regressões lineares com controles & Duas regressões não lineares com controles \\ \midrule %% TinyTableHeader
(Intercept)                                    & \num{4.123}   & \num{1.938}     & \num{-50.636}  & \num{-52.078}   \\
& (\num{0.034}) & (\num{0.356})   & (\num{0.023})  & (\num{0.029})   \\
vitoria\_pp                                   & \num{-0.555}  & \num{2.515}     & \num{-4.052}   & \num{-4.428}    \\
& (\num{0.855}) & (\num{0.507})   & (\num{0.223})  & (\num{0.179})   \\
votos\_razao\_pp\_centr                     & \num{56.142}  & \num{-188.732}  & \num{117.048}  & \num{10.106}    \\
& (\num{0.225}) & (\num{0.478})   & (\num{0.132})  & (\num{0.978})   \\
vitoria\_pp × votos\_razao\_pp\_centr      & \num{-96.373} & \num{13.905}    & \num{-121.781} & \num{190.213}   \\
& (\num{0.278}) & (\num{0.968})   & (\num{0.138})  & (\num{0.636})   \\
votos\_razao\_pp\_centr\_sq                &                & \num{-4911.336} &                 & \num{-2110.836} \\
&                & (\num{0.381})   &                 & (\num{0.792})   \\
vitoria\_pp × votos\_razao\_pp\_centr\_sq &                & \num{7799.865}  &                 & \num{-2263.528} \\
&                & (\num{0.259})   &                 & (\num{0.786})   \\
regiaoNordeste                                 &                &                  & \num{3.365}    & \num{3.522}     \\
&                &                  & (\num{0.037})  & (\num{0.092})   \\
regiaoNorte                                    &                &                  & \num{8.882}    & \num{8.737}     \\
&                &                  & (\num{0.097})  & (\num{0.102})   \\
regiaoSudeste                                  &                &                  & \num{5.302}    & \num{5.437}     \\
&                &                  & (\num{0.004})  & (\num{0.007})   \\
regiaoSul                                      &                &                  & \num{0.330}    & \num{0.164}     \\
&                &                  & (\num{0.579})  & (\num{0.834})   \\
pop                                            &                &                  & \num{0.000}    & \num{0.000}     \\
&                &                  & (\num{0.249})  & (\num{0.292})   \\
PIBpc                                          &                &                  & \num{0.000}    & \num{0.000}     \\
&                &                  & (\num{0.397})  & (\num{0.323})   \\
taxa\_escolarizacao                           &                &                  & \num{54.819}   & \num{55.205}    \\
&                &                  & (\num{0.019})  & (\num{0.019})   \\
mortalidade\_infantil                         &                &                  & \num{-0.025}   & \num{-0.028}    \\
&                &                  & (\num{0.384})  & (\num{0.371})   \\
Num.Obs.                                       & \num{487}     & \num{487}       & \num{316}      & \num{316}       \\
R2                                             & \num{0.002}   & \num{0.005}     & \num{0.038}    & \num{0.042}     \\
R2 Adj.                                        & \num{-0.004}  & \num{-0.005}    & \num{0.004}    & \num{0.000}     \\
AIC                                            & \num{4012.3}  & \num{4014.9}    & \num{2550.6}   & \num{2553.5}    \\
BIC                                            & \num{4033.2}  & \num{4044.3}    & \num{2599.4}   & \num{2609.8}    \\
RMSE                                           & \num{14.73}   & \num{14.71}     & \num{13.14}    & \num{13.12}     \\
\bottomrule
\end{tblr}
\end{table}

\subsection{3.3) Para emendas de
bancada}\label{para-emendas-de-bancada-1}

\subsubsection{3.3.1) Valores absolutos}\label{valores-absolutos-2}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Duas regressões lineares com controle de razão de votos do PP}
\NormalTok{regs\_lineares }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr, }\AttributeTok{data =}\NormalTok{ dt\_bancada)}

\CommentTok{\# Duas regressões com linearidade flexibilizada e controle de razão de votos do PP}
\NormalTok{regs\_flexiveis }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr }\SpecialCharTok{+}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr\_sq, }\AttributeTok{data =}\NormalTok{ dt\_bancada)}

\CommentTok{\# Duas regressões lineares com controles}
\NormalTok{regs\_lineares\_controles }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr }\SpecialCharTok{+}\NormalTok{ regiao }\SpecialCharTok{+}\NormalTok{ pop }\SpecialCharTok{+}\NormalTok{ PIBpc }\SpecialCharTok{+}\NormalTok{ taxa\_escolarizacao }\SpecialCharTok{+}\NormalTok{ mortalidade\_infantil, }\AttributeTok{data =}\NormalTok{ dt\_bancada)}

\CommentTok{\# Duas regressões com linearidade flexibilizada e controles}
\NormalTok{regs\_flexiveis\_controles }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr }\SpecialCharTok{+}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr\_sq }\SpecialCharTok{+}\NormalTok{ regiao }\SpecialCharTok{+}\NormalTok{ pop }\SpecialCharTok{+}\NormalTok{ PIBpc }\SpecialCharTok{+}\NormalTok{ taxa\_escolarizacao }\SpecialCharTok{+}\NormalTok{ mortalidade\_infantil, }\AttributeTok{data =}\NormalTok{ dt\_bancada)}

\CommentTok{\# Resultados}
\FunctionTok{modelsummary}\NormalTok{(}\FunctionTok{list}\NormalTok{(}
  \StringTok{"Duas regressões lineares"} \OtherTok{=}\NormalTok{ regs\_lineares,}
  \StringTok{"Duas regressões não lineares"} \OtherTok{=}\NormalTok{ regs\_flexiveis,}
  \StringTok{"Duas regressões lineares com controles"} \OtherTok{=}\NormalTok{ regs\_lineares\_controles,}
  \StringTok{"Duas regressões não lineares com controles"} \OtherTok{=}\NormalTok{ regs\_flexiveis\_controles}
\NormalTok{),}
\AttributeTok{statistic =} \StringTok{"p.value"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Warning in attr(.knitEnv$meta, "knit_meta_id"): 'xfun::attr()' is deprecated.
Use 'xfun::attr2()' instead.
See help("Deprecated")
Warning in attr(.knitEnv$meta, "knit_meta_id"): 'xfun::attr()' is deprecated.
Use 'xfun::attr2()' instead.
See help("Deprecated")
\end{verbatim}

\begin{table}
\centering
\begin{tblr}[         %% tabularray outer open
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]Q[]Q[]Q[]},
column{1}={halign=l,},
column{2}={halign=c,},
column{3}={halign=c,},
column{4}={halign=c,},
column{5}={halign=c,},
hline{30}={1,2,3,4,5}{solid, 0.05em, black},
}                     %% tabularray inner close
\toprule
& Duas regressões lineares & Duas regressões não lineares & Duas regressões lineares com controles & Duas regressões não lineares com controles \\ \midrule %% TinyTableHeader
(Intercept)                                    & \num{-195575.103}   & \num{7.512895e+04}  & \num{3171485.281}  & \num{3.739230e+06}  \\
& (\num{0.314})       & (\num{0.659})       & (\num{0.508})      & (\num{0.412})       \\
vitoria\_pp                                   & \num{411924.061}    & \num{-1.676115e+05} & \num{176927.024}   & \num{-7.148800e+05} \\
& (\num{0.110})       & (\num{0.472})       & (\num{0.458})      & (\num{0.064})       \\
votos\_razao\_pp\_centr                     & \num{-13868541.399} & \num{1.647897e+07}  & \num{-5633089.446} & \num{5.342972e+07}  \\
& (\num{0.261})       & (\num{0.561})       & (\num{0.322})      & (\num{0.168})       \\
vitoria\_pp × votos\_razao\_pp\_centr      & \num{17964574.322}  & \num{3.458461e+07}  & \num{8252746.968}  & \num{3.879806e+06}  \\
& (\num{0.176})       & (\num{0.423})       & (\num{0.317})      & (\num{0.926})       \\
votos\_razao\_pp\_centr\_sq                &                      & \num{6.086675e+08}  &                     & \num{1.168740e+09}  \\
&                      & (\num{0.445})       &                     & (\num{0.125})       \\
vitoria\_pp × votos\_razao\_pp\_centr\_sq &                      & \num{-1.616624e+09} &                     & \num{-2.332140e+09} \\
&                      & (\num{0.115})       &                     & (\num{0.070})       \\
regiaoNordeste                                 &                      &                      & \num{-1290422.619} & \num{-1.383017e+06} \\
&                      &                      & (\num{0.255})      & (\num{0.230})       \\
regiaoNorte                                    &                      &                      & \num{-448779.914}  & \num{-5.779277e+05} \\
&                      &                      & (\num{0.767})      & (\num{0.712})       \\
regiaoSudeste                                  &                      &                      & \num{-1591501.908} & \num{-1.677246e+06} \\
&                      &                      & (\num{0.170})      & (\num{0.154})       \\
regiaoSul                                      &                      &                      & \num{-1194743.239} & \num{-1.359656e+06} \\
&                      &                      & (\num{0.275})      & (\num{0.239})       \\
pop                                            &                      &                      & \num{39.417}       & \num{3.919600e+01}  \\
&                      &                      & (\num{<0.001})     & (\num{<0.001})      \\
PIBpc                                          &                      &                      & \num{-0.420}       & \num{2.100000e-01}  \\
&                      &                      & (\num{0.775})      & (\num{0.902})       \\
taxa\_escolarizacao                           &                      &                      & \num{-3163013.862} & \num{-3.070454e+06} \\
&                      &                      & (\num{0.510})      & (\num{0.495})       \\
mortalidade\_infantil                         &                      &                      & \num{18565.631}    & \num{1.680733e+04}  \\
&                      &                      & (\num{0.002})      & (\num{0.007})       \\
Num.Obs.                                       & \num{487}           & \num{487}           & \num{316}          & \num{316}           \\
R2                                             & \num{0.004}         & \num{0.010}         & \num{0.611}        & \num{0.617}         \\
R2 Adj.                                        & \num{-0.002}        & \num{0.000}         & \num{0.597}        & \num{0.601}         \\
AIC                                            & \num{15734.6}       & \num{15735.5}       & \num{10066.9}      & \num{10066.1}       \\
BIC                                            & \num{15755.6}       & \num{15764.9}       & \num{10115.7}      & \num{10122.5}       \\
RMSE                                           & \num{2484166.40}    & \num{2476299.61}    & \num{1921441.91}   & \num{1906903.90}    \\
\bottomrule
\end{tblr}
\end{table}

\subsubsection{\texorpdfstring{3.3.2) Valores \emph{per
capita}}{3.3.2) Valores per capita}}\label{valores-per-capita-2}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Duas regressões lineares com controle de razão de votos do PP}
\NormalTok{regs\_lineares }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca\_pc }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr, }\AttributeTok{data =}\NormalTok{ dt\_bancada)}

\CommentTok{\# Duas regressões com linearidade flexibilizada e controle de razão de votos do PP}
\NormalTok{regs\_flexiveis }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca\_pc }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr }\SpecialCharTok{+}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr\_sq, }\AttributeTok{data =}\NormalTok{ dt\_bancada)}

\CommentTok{\# Duas regressões lineares com controles}
\NormalTok{regs\_lineares\_controles }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca\_pc }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr }\SpecialCharTok{+}\NormalTok{ regiao }\SpecialCharTok{+}\NormalTok{ pop }\SpecialCharTok{+}\NormalTok{ PIBpc }\SpecialCharTok{+}\NormalTok{ taxa\_escolarizacao }\SpecialCharTok{+}\NormalTok{ mortalidade\_infantil, }\AttributeTok{data =}\NormalTok{ dt\_bancada)}

\CommentTok{\# Duas regressões com linearidade flexibilizada e controles}
\NormalTok{regs\_flexiveis\_controles }\OtherTok{\textless{}{-}} \FunctionTok{lm\_robust}\NormalTok{(valor\_empenhado\_ipca\_pc }\SpecialCharTok{\textasciitilde{}}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr }\SpecialCharTok{+}\NormalTok{ vitoria\_pp}\SpecialCharTok{*}\NormalTok{votos\_razao\_pp\_centr\_sq }\SpecialCharTok{+}\NormalTok{ regiao }\SpecialCharTok{+}\NormalTok{ pop }\SpecialCharTok{+}\NormalTok{ PIBpc }\SpecialCharTok{+}\NormalTok{ taxa\_escolarizacao }\SpecialCharTok{+}\NormalTok{ mortalidade\_infantil, }\AttributeTok{data =}\NormalTok{ dt\_bancada)}

\CommentTok{\# Resultados}
\FunctionTok{modelsummary}\NormalTok{(}\FunctionTok{list}\NormalTok{(}
  \StringTok{"Duas regressões lineares"} \OtherTok{=}\NormalTok{ regs\_lineares,}
  \StringTok{"Duas regressões não lineares"} \OtherTok{=}\NormalTok{ regs\_flexiveis,}
  \StringTok{"Duas regressões lineares com controles"} \OtherTok{=}\NormalTok{ regs\_lineares\_controles,}
  \StringTok{"Duas regressões não lineares com controles"} \OtherTok{=}\NormalTok{ regs\_flexiveis\_controles}
\NormalTok{),}
\AttributeTok{statistic =} \StringTok{"p.value"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Warning in attr(.knitEnv$meta, "knit_meta_id"): 'xfun::attr()' is deprecated.
Use 'xfun::attr2()' instead.
See help("Deprecated")
Warning in attr(.knitEnv$meta, "knit_meta_id"): 'xfun::attr()' is deprecated.
Use 'xfun::attr2()' instead.
See help("Deprecated")
\end{verbatim}

\begin{table}
\centering
\begin{tblr}[         %% tabularray outer open
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]Q[]Q[]Q[]},
column{1}={halign=l,},
column{2}={halign=c,},
column{3}={halign=c,},
column{4}={halign=c,},
column{5}={halign=c,},
hline{30}={1,2,3,4,5}{solid, 0.05em, black},
}                     %% tabularray inner close
\toprule
& Duas regressões lineares & Duas regressões não lineares & Duas regressões lineares com controles & Duas regressões não lineares com controles \\ \midrule %% TinyTableHeader
(Intercept)                                    & \num{-0.650}   & \num{-10.654}    & \num{123.439}  & \num{102.997}    \\
& (\num{0.413})  & (\num{0.335})    & (\num{0.671})  & (\num{0.724})    \\
vitoria\_pp                                   & \num{1.515}    & \num{10.426}     & \num{-7.465}   & \num{12.448}     \\
& (\num{0.152})  & (\num{0.346})    & (\num{0.402})  & (\num{0.413})    \\
votos\_razao\_pp\_centr                     & \num{-267.723} & \num{-1389.295}  & \num{-69.192}  & \num{-1997.138}  \\
& (\num{0.274})  & (\num{0.338})    & (\num{0.638})  & (\num{0.347})    \\
vitoria\_pp × votos\_razao\_pp\_centr      & \num{275.959}  & \num{1563.845}   & \num{86.597}   & \num{1634.302}   \\
& (\num{0.260})  & (\num{0.283})    & (\num{0.644})  & (\num{0.300})    \\
votos\_razao\_pp\_centr\_sq                &                 & \num{-22494.902} &                 & \num{-38125.732} \\
&                 & (\num{0.355})    &                 & (\num{0.352})    \\
vitoria\_pp × votos\_razao\_pp\_centr\_sq &                 & \num{18925.686}  &                 & \num{46157.358}  \\
&                 & (\num{0.439})    &                 & (\num{0.395})    \\
regiaoNordeste                                 &                 &                   & \num{-3.823}   & \num{-0.851}     \\
&                 &                   & (\num{0.609})  & (\num{0.926})    \\
regiaoNorte                                    &                 &                   & \num{89.551}   & \num{92.020}     \\
&                 &                   & (\num{0.340})  & (\num{0.340})    \\
regiaoSudeste                                  &                 &                   & \num{-4.253}   & \num{-1.547}     \\
&                 &                   & (\num{0.595})  & (\num{0.872})    \\
regiaoSul                                      &                 &                   & \num{-6.271}   & \num{-3.038}     \\
&                 &                   & (\num{0.383})  & (\num{0.720})    \\
pop                                            &                 &                   & \num{0.000}    & \num{0.000}      \\
&                 &                   & (\num{0.232})  & (\num{0.198})    \\
PIBpc                                          &                 &                   & \num{0.000}    & \num{0.000}      \\
&                 &                   & (\num{0.637})  & (\num{0.750})    \\
taxa\_escolarizacao                           &                 &                   & \num{-134.764} & \num{-135.227}   \\
&                 &                   & (\num{0.651})  & (\num{0.661})    \\
mortalidade\_infantil                         &                 &                   & \num{0.820}    & \num{0.849}      \\
&                 &                   & (\num{0.284})  & (\num{0.288})    \\
Num.Obs.                                       & \num{487}      & \num{487}        & \num{316}      & \num{316}        \\
R2                                             & \num{0.004}    & \num{0.006}      & \num{0.114}    & \num{0.118}      \\
R2 Adj.                                        & \num{-0.003}   & \num{-0.005}     & \num{0.082}    & \num{0.080}      \\
AIC                                            & \num{5335.5}   & \num{5338.4}     & \num{3580.6}   & \num{3583.1}     \\
BIC                                            & \num{5356.4}   & \num{5367.8}     & \num{3629.4}   & \num{3639.5}     \\
RMSE                                           & \num{57.32}    & \num{57.26}      & \num{67.05}    & \num{66.89}      \\
\bottomrule
\end{tblr}
\end{table}




\end{document}
